import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useAuth } from "@/components/AuthProvider";
import { updateAccountType } from "@/lib/api";
import { theme } from "@/lib/theme";

type Choice = "driver" | "provider";
export default function AccountTypeScreen() {
  const { refresh } = useAuth();
  const [choice, setChoice] = useState<Choice | null>(null);
  const [company, setCompany] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const save = async () => { if (!choice) return setError("Wybierz typ konta."); if (choice === "provider" && company.trim().length < 2) return setError("Podaj nazwę firmy lub floty."); setSaving(true); setError(null); try { await updateAccountType(choice, choice === "provider" ? company : undefined); await refresh(); router.replace("/(tabs)" as never); } catch (reason) { setError(reason instanceof Error ? reason.message : "Nie udało się zapisać profilu."); } finally { setSaving(false); } };
  return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>KONFIGURACJA KONTA</Text><Text accessibilityRole="header" style={styles.title}>Jak korzystasz z PlusPuls?</Text><Text style={styles.subtitle}>Wybór dopasowuje funkcje kierowcy i daje administratorowi kontekst podczas weryfikacji.</Text><ChoiceCard active={choice === "driver"} icon="car-outline" title="Niezależny kierowca" detail="Mapa popytu, plan dnia, strefy i zarobki" onPress={() => setChoice("driver")} /><ChoiceCard active={choice === "provider"} icon="business-outline" title="Firma / flota" detail="Koordynacja kierowców i kontekst operacyjny" onPress={() => setChoice("provider")} />{choice === "provider" ? <TextInput accessibilityLabel="Nazwa firmy lub floty" value={company} onChangeText={setCompany} maxLength={120} placeholder="Nazwa firmy lub floty" placeholderTextColor={theme.muted} style={styles.input} /> : null}{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<Pressable accessibilityRole="button" onPress={() => void save()} disabled={saving || !choice} style={[styles.button, (saving || !choice) && { opacity: .45 }]}>{saving ? <ActivityIndicator color={theme.background} /> : <Text style={styles.buttonText}>Zapisz profil</Text>}</Pressable></ScrollView></SafeAreaView>;
}
function ChoiceCard({ active, icon, title, detail, onPress }: { active: boolean; icon: keyof typeof Ionicons.glyphMap; title: string; detail: string; onPress: () => void }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: active }} onPress={onPress} style={[styles.choice, active && styles.choiceActive]}><View style={styles.choiceIcon}><Ionicons name={icon} size={25} color={active ? theme.primary : theme.muted} /></View><View style={{ flex: 1 }}><Text style={styles.choiceTitle}>{title}</Text><Text style={styles.choiceDetail}>{detail}</Text></View>{active ? <Ionicons name="checkmark-circle" size={24} color={theme.primary} /> : null}</Pressable>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: theme.background }, content: { flexGrow: 1, justifyContent: "center", padding: 22, gap: 12 }, eyebrow: { color: theme.primary, fontSize: 10, fontWeight: "900", letterSpacing: 1.3 }, title: { color: theme.text, fontSize: 27, lineHeight: 34, fontWeight: "900" }, subtitle: { color: theme.muted, fontSize: 12, lineHeight: 18, marginBottom: 7 }, choice: { minHeight: 88, flexDirection: "row", alignItems: "center", gap: 12, padding: 14, borderRadius: 18, borderWidth: 1, borderColor: theme.border, backgroundColor: theme.surface }, choiceActive: { borderColor: theme.primary, backgroundColor: "rgba(46,230,166,.07)" }, choiceIcon: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: 15, backgroundColor: theme.surfaceRaised }, choiceTitle: { color: theme.text, fontSize: 13, fontWeight: "900" }, choiceDetail: { color: theme.muted, fontSize: 10, lineHeight: 15, marginTop: 3 }, input: { minHeight: 50, paddingHorizontal: 14, borderRadius: 14, borderWidth: 1, borderColor: theme.border, color: theme.text, backgroundColor: theme.surface }, error: { color: theme.danger, fontSize: 10.5 }, button: { minHeight: 52, alignItems: "center", justifyContent: "center", borderRadius: 15, backgroundColor: theme.primary, marginTop: 4 }, buttonText: { color: theme.background, fontSize: 12, fontWeight: "900" } });
