import { router, useLocalSearchParams } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { PageHeader } from "@/components/PageHeader";
import { TRUST_SECTIONS } from "@/lib/trust";
import { theme } from "@/lib/theme";

export default function TrustScreen() {
  const params = useLocalSearchParams<{ section?: string }>();
  const active = TRUST_SECTIONS.find((item) => item.id === params.section) ?? TRUST_SECTIONS[0];
  return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><PageHeader title={active.title} subtitle="PlusPuls · trust & access" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.nav}>{TRUST_SECTIONS.map((item) => <Pressable key={item.id} accessibilityRole="button" accessibilityState={{ selected: item.id === active.id }} onPress={() => router.replace(`/trust/${item.id}` as never)} style={[styles.chip, item.id === active.id && styles.chipActive]}><Text style={[styles.chipText, item.id === active.id && styles.chipTextActive]}>{item.label}</Text></Pressable>)}</ScrollView>{active.items.map(([title, paragraphs]) => <View key={title} style={styles.card}><Text accessibilityRole="header" style={styles.cardTitle}>{title}</Text>{paragraphs.map((paragraph) => <Text key={paragraph} style={styles.paragraph}>{paragraph}</Text>)}</View>)}{active.id === "speak-up" ? <Pressable accessibilityRole="button" onPress={() => router.push("/feedback" as never)} style={styles.button}><Text style={styles.buttonText}>Zgłoś problem</Text></Pressable> : null}<Text style={styles.footer}>Treści odpowiadają centrum zaufania wersji webowej. Przed publiczną premierą należy uzupełnić pełną tożsamość administratora danych i kontakt prawny.</Text></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: theme.background }, content: { padding: 18, paddingBottom: 42 }, nav: { gap: 8, paddingBottom: 14 }, chip: { minHeight: 42, justifyContent: "center", paddingHorizontal: 14, borderRadius: 12, borderWidth: 1, borderColor: theme.border, backgroundColor: theme.surface }, chipActive: { borderColor: theme.primary, backgroundColor: "rgba(46,230,166,.08)" }, chipText: { color: theme.muted, fontSize: 10.5, fontWeight: "800" }, chipTextActive: { color: theme.primary }, card: { padding: 16, borderRadius: 18, borderWidth: 1, borderColor: theme.border, backgroundColor: theme.surface, marginBottom: 10 }, cardTitle: { color: theme.text, fontSize: 16, fontWeight: "900", marginBottom: 8 }, paragraph: { color: theme.muted, fontSize: 11, lineHeight: 17, marginTop: 5 }, button: { minHeight: 50, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: theme.primary, marginTop: 3 }, buttonText: { color: theme.background, fontSize: 12, fontWeight: "900" }, footer: { color: theme.muted, fontSize: 9.5, lineHeight: 14, marginTop: 16 } });
