export const LIVE_DEMAND_MAP_HTML = String.raw`<!doctype html>
<html lang="pl">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" />
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-pluspuls-map-v1' https://cdn.jsdelivr.net; style-src 'unsafe-inline' https://cdn.jsdelivr.net; img-src data: https://*.basemaps.cartocdn.com; font-src data:; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIINfQ3yn5ccAHs70q7jyhfYwteP4J5i4s=" crossorigin="anonymous" />
  <style>
    :root{color-scheme:dark;--bg:#111923;--surface:rgba(16,22,31,.94);--raised:#1a1f2e;--border:#273044;--text:#eff1f6;--muted:#aab1c2;--teal:#20dca0;--amber:#f59e0b;--coral:#f43f5e}
    *{box-sizing:border-box}html,body,#map{height:100%;width:100%;margin:0;overflow:hidden;background:var(--bg);font-family:system-ui,-apple-system,"Segoe UI",sans-serif}.leaflet-container{background:#18212b}.leaflet-tile-pane{filter:saturate(.72) contrast(1.08) brightness(.78)}.leaflet-tile{image-rendering:auto;backface-visibility:hidden}
    #map-shell{position:fixed;inset:0;border:1px solid rgba(46,230,166,.3);overflow:hidden;background:#111923}
    #vignette{display:none}
    .panel{border:1px solid rgba(46,230,166,.28);background:linear-gradient(180deg,rgba(18,26,37,.94),rgba(10,16,25,.92));box-shadow:0 14px 38px rgba(0,0,0,.55),0 0 22px rgba(46,230,166,.1);backdrop-filter:blur(14px);border-radius:13px;color:var(--text)}
    #title{position:absolute;left:10px;top:10px;z-index:900;padding:9px 11px;display:flex;gap:8px;align-items:center;max-width:185px}.brand{color:var(--teal);font-size:9px;font-weight:900;letter-spacing:.18em;text-transform:uppercase}.subtitle{font-size:10px;color:#c8cedc;margin-top:2px}.navmark{color:var(--teal);font-size:18px;line-height:1}
    #cockpit{position:absolute;right:8px;top:8px;z-index:1000;width:150px;max-height:calc(100% - 16px);overflow:auto;display:flex;flex-direction:column;gap:7px;scrollbar-width:none}#cockpit::-webkit-scrollbar{display:none}.section{padding:8px}.section-head{display:flex;justify-content:space-between;align-items:center;gap:6px;margin-bottom:6px}.section-title{font-size:8px;font-weight:900;letter-spacing:.12em;text-transform:uppercase}.section-meta{font-size:7px;color:var(--muted)}
    .layers{display:grid;grid-template-columns:1fr;gap:4px}.layer{min-height:34px;text-align:left;border:1px solid rgba(139,143,168,.25);border-radius:9px;background:rgba(16,23,36,.82);color:var(--muted);padding:5px 7px;touch-action:manipulation}.layer.active{border-color:rgba(46,230,166,.58);background:rgba(46,230,166,.14);color:var(--text);box-shadow:0 0 14px rgba(46,230,166,.1)}.layer b{display:block;font-size:8px}.layer small{display:block;font-size:6.5px;opacity:.72;margin-top:1px}
    .times{display:flex;flex-wrap:wrap;gap:4px}.time{min-width:38px;min-height:32px;border:0;border-radius:8px;background:#141b29;color:var(--muted);font-size:8px;font-weight:900;padding:5px;touch-action:manipulation}.time.active{background:var(--teal);color:#07110e;box-shadow:0 0 15px rgba(46,230,166,.3)}#narrative{font-size:8px;color:var(--muted);line-height:1.35;margin:7px 0 0}.legend{display:flex;flex-wrap:wrap;gap:6px 8px;font-size:7px;color:#dce1eb}.legend span{display:flex;align-items:center;gap:4px}.swatch{width:7px;height:7px;border-radius:50%;display:inline-block}.hex{border-radius:2px}.leaflet-control-attribution{font-size:7px!important;background:rgba(5,8,13,.75)!important;color:#aeb4c4!important}.leaflet-control-attribution a{color:#aeb4c4!important}.leaflet-control-zoom{border:0!important}.leaflet-control-zoom a{background:rgba(18,22,34,.95)!important;color:var(--text)!important;border-color:var(--border)!important}.leaflet-popup-content-wrapper,.leaflet-popup-tip{background:rgba(18,22,34,.98)!important;color:var(--text)!important;border:1px solid rgba(46,230,166,.22)}.leaflet-popup-content{margin:10px 12px;font-size:11px}#sync{position:absolute;left:10px;bottom:10px;z-index:900;padding:7px 9px;font-size:8px;color:var(--muted)}
    @media(max-width:390px){#title{max-width:145px}.subtitle{font-size:8px}#cockpit{width:138px}.section{padding:7px}.layer{padding:5px}.layer small{font-size:6px}}
    @media(max-height:590px){#cockpit{width:158px}.layer{min-height:36px}.section{padding:7px}.legend-panel{display:none}}
    @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}
  </style>
  <script src="https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin="anonymous"></script>
</head>
<body>
  <main id="map-shell" aria-label="Interaktywna mapa natężenia ruchu w Krakowie">
    <div id="map"></div><div id="vignette"></div>
    <div id="title" class="panel"><div class="navmark">⌁</div><div><div class="brand">PlusPuls Live</div><div class="subtitle">Popyt, trasy i ruch w Krakowie</div></div></div>
    <aside id="cockpit" aria-label="Sterowanie mapą">
      <section class="panel section"><div class="section-head"><span class="section-title">Warstwy</span><span id="layer-count" class="section-meta">3/3</span></div><div class="layers">
        <button class="layer active" data-layer="heatmap" aria-pressed="true"><b>● Heatmapa</b><small>popyt strefowy</small></button>
        <button class="layer active" data-layer="traffic" aria-pressed="true"><b>● Ruch</b><small>sygnały drogowe</small></button>
        <button class="layer active" data-layer="routes" aria-pressed="true"><b>● Trasy</b><small>geometria przejazdu</small></button>
      </div></section>
      <section class="panel section"><div class="section-head"><span class="section-title">Horyzont</span><span id="target-time" class="section-meta">LIVE</span></div><div class="times">
        <button class="time active" data-hours="0" data-minutes="0">Live</button><button class="time" data-hours="0" data-minutes="30">+30m</button><button class="time" data-hours="1" data-minutes="0">+1h</button><button class="time" data-hours="2" data-minutes="0">+2h</button><button class="time" data-hours="3" data-minutes="0">+3h</button><button class="time" data-hours="6" data-minutes="0">+6h</button><button class="time" data-hours="12" data-minutes="0">+12h</button>
      </div><p id="narrative">Aktualny popyt i ruch drogowy.</p></section>
    </aside>
    <div id="sync" class="panel">Łączenie z sygnałami PlusPuls…</div>
  </main>
  <script nonce="pluspuls-map-v1">
  (function(){
    'use strict';
    var CENTER=[50.0647,19.945], layers={heatmap:true,traffic:true,routes:true};
    var payload={cells:[],roads:[],routes:[],position:null,narrative:'',targetTime:'LIVE',generatedAt:null,error:null};
    var map=L.map('map',{zoomControl:false,preferCanvas:true,attributionControl:true,minZoom:9,maxZoom:19,zoomSnap:1,zoomDelta:1,touchZoom:true,doubleClickZoom:true,tap:false,zoomAnimation:false,fadeAnimation:false,markerZoomAnimation:false}).setView(CENTER,12);
    L.control.zoom({position:'bottomleft'}).addTo(map);
    var tiles=L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png',{subdomains:'abcd',maxNativeZoom:18,maxZoom:19,attribution:'&copy; OpenStreetMap &copy; CARTO',crossOrigin:true,detectRetina:false,updateWhenZooming:true,updateWhenIdle:true,updateInterval:160,keepBuffer:2}).addTo(map);
    map.createPane('heatPane');map.getPane('heatPane').style.zIndex='350';
    map.createPane('trafficPane');map.getPane('trafficPane').style.zIndex='420';map.getPane('trafficPane').style.pointerEvents='none';
    map.createPane('routePane');map.getPane('routePane').style.zIndex='480';
    map.createPane('driverPane');map.getPane('driverPane').style.zIndex='520';
    var heatRenderer=L.canvas({pane:'heatPane',padding:.75,tolerance:0}),trafficRenderer=L.canvas({pane:'trafficPane',padding:.75,tolerance:0}),routeRenderer=L.canvas({pane:'routePane',padding:.75,tolerance:8}),driverRenderer=L.canvas({pane:'driverPane',padding:.5,tolerance:8});
    var heatGroup=L.layerGroup().addTo(map),trafficGroup=L.layerGroup().addTo(map),routeGroup=L.layerGroup().addTo(map),driverGroup=L.layerGroup().addTo(map);
    function finite(n){return typeof n==='number'&&isFinite(n)}function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
    function hex(lat,lng,r){var pts=[],mLat=111000,mLng=111000*Math.cos(lat*Math.PI/180);for(var i=0;i<6;i++){var a=i*Math.PI/3;pts.push([lat+r*Math.sin(a)/mLat,lng+r*Math.cos(a)/mLng])}return pts}
    function heatVisual(score){score=clamp(score,0,100);if(score>=90)return['#ff3159',.5];if(score>=75)return['#ffad32',.44];if(score>=55)return['#19e6a2',.4];if(score>=35)return['#12b981',.34];return['#64748b',.24]}
    function safeText(value){return String(value==null?'':value).slice(0,120)}
    function popup(title,detail){var wrap=document.createElement('div'),strong=document.createElement('strong'),small=document.createElement('div');strong.textContent=safeText(title);small.textContent=safeText(detail);small.style.color='#9298af';small.style.marginTop='4px';wrap.appendChild(strong);wrap.appendChild(small);return wrap}
    var navigationFitted=false;
    function renderHeat(){heatGroup.clearLayers();if(!layers.heatmap)return;(payload.cells||[]).slice(0,700).forEach(function(c){if(!finite(c.lat)||!finite(c.lng)||!finite(c.radius)||!finite(c.score))return;var v=heatVisual(c.score),r=clamp(c.radius,80,1800);L.polygon(hex(c.lat,c.lng,r),{pane:'heatPane',renderer:heatRenderer,color:v[0],fillColor:v[0],fillOpacity:v[1],weight:1.25,opacity:.82,interactive:false}).addTo(heatGroup)})}
    function renderRoutes(){routeGroup.clearLayers();if(!layers.routes)return;(payload.routes||[]).slice(0,12).forEach(function(r){var points=(r.geometry||[]).filter(function(p){return Array.isArray(p)&&finite(p[0])&&finite(p[1])}).slice(0,240);if(points.length<2)return;var nav=r.role==='drive_to_pickup',color=nav?'#0ea5e9':r.role==='nearest_profitable'?'#00d998':'#f59e0b';L.polyline(points,{pane:'routePane',renderer:routeRenderer,color:'#071018',weight:nav?11:9,opacity:.88,lineCap:'round',lineJoin:'round',interactive:false}).addTo(routeGroup);L.polyline(points,{pane:'routePane',renderer:routeRenderer,color:color,weight:nav?6:r.role==='nearest_profitable'?5:4,opacity:1,dashArray:nav?null:(r.role==='nearest_profitable'?'14 8':'6 8'),lineCap:'round',lineJoin:'round'}).bindPopup(popup(r.fromShort+' → '+r.toShort,nav?'Dojazd GPS do rekomendowanej strefy':(finite(r.estimatedPricePLN)?Math.round(r.estimatedPricePLN)+' PLN':''))).addTo(routeGroup);if(nav&&!navigationFitted){navigationFitted=true;setTimeout(function(){map.fitBounds(L.latLngBounds(points),{paddingTopLeft:[24,64],paddingBottomRight:[170,64],maxZoom:15,animate:false})},0)}})}
    function renderDriver(){driverGroup.clearLayers();var p=payload.position;if(!p||!finite(p.lat)||!finite(p.lng))return;L.circle([p.lat,p.lng],{pane:'driverPane',renderer:driverRenderer,radius:clamp(p.accuracy||60,20,1000),color:'#7dd3fc',fillColor:'#38bdf8',fillOpacity:.1,weight:2,dashArray:'5 5'}).addTo(driverGroup);L.circleMarker([p.lat,p.lng],{pane:'driverPane',renderer:driverRenderer,radius:8,color:'#effcff',fillColor:'#0ea5e9',fillOpacity:1,weight:3}).bindPopup(popup('Twoja lokalizacja','GPS aktywny')).addTo(driverGroup)}
    function renderAll(){renderHeat();renderRoutes();renderDriver();prepareRoads();document.getElementById('narrative').textContent=safeText(payload.narrative||'Aktualny popyt i ruch drogowy.');document.getElementById('target-time').textContent=safeText(payload.targetTime||'LIVE');var sync=document.getElementById('sync'),summary=(payload.roads||[]).length+' dróg · '+(payload.cells||[]).length+' pól ciepła · '+(payload.routes||[]).length+' tras'+(payload.position?' · GPS':'');sync.textContent=payload.error?safeText(payload.error+' · '+summary):summary;sync.style.color=payload.error?'#ffb547':'#d6dbe7'}
    document.querySelectorAll('.layer').forEach(function(btn){btn.addEventListener('click',function(){var id=btn.getAttribute('data-layer');layers[id]=!layers[id];btn.classList.toggle('active',layers[id]);btn.setAttribute('aria-pressed',String(layers[id]));var b=btn.querySelector('b');if(b)b.textContent=(layers[id]?'● ':'○ ')+({heatmap:'Heatmapa',traffic:'Ruch',routes:'Trasy'}[id]||id);document.getElementById('layer-count').textContent=Object.keys(layers).filter(function(k){return layers[k]}).length+'/3';renderAll()})});
    document.querySelectorAll('.time').forEach(function(btn){btn.addEventListener('click',function(){document.querySelectorAll('.time').forEach(function(b){b.classList.remove('active')});btn.classList.add('active');var h=Number(btn.getAttribute('data-hours')),m=Number(btn.getAttribute('data-minutes'));if(window.ReactNativeWebView)window.ReactNativeWebView.postMessage(JSON.stringify({type:'time',hours:h,minutes:m,label:btn.textContent}))})});
    function receive(event){try{var data=JSON.parse(event.data);if(data&&data.type==='map-data'){payload=data.payload||payload;renderAll()}}catch(_){}}
    window.addEventListener('message',receive);document.addEventListener('message',receive);

    var prepared=[],visible=[],trafficDots=[],zoom=map.getZoom(),started=performance.now(),lastFrame=0;
    function norm(v){return finite(v)?clamp(v,0,1):0}function roadPriority(r){var p={motorway:5,trunk:4,primary:3,secondary:2,tertiary:1};return(p[r.highway]||0)*10+norm(r.intensity)*12}
    function visual(i){return i>=.7?{color:'#ff5470',alpha:.98,scale:1.18}:i>=.42?{color:'#ffb547',alpha:.94,scale:1.08}:{color:'#2ee6a6',alpha:.9,scale:1}}
    function prepareRoads(){prepared=(payload.roads||[]).slice(0,180).flatMap(function(r){var ll=(r.geometry||[]).filter(function(p){return Array.isArray(p)&&finite(p[0])&&finite(p[1])}).slice(0,180).map(function(p){return L.latLng(p[0],p[1])});if(ll.length<2)return[];var cum=[0];for(var i=1;i<ll.length;i++)cum.push(cum[i-1]+ll[i-1].distanceTo(ll[i]));var total=cum[cum.length-1];if(total<50)return[];var intensity=norm(r.intensity),count=Math.min(18,Math.max(2,Math.round(total/300*(.58+intensity*.72)))),phases=[];for(i=0;i<count;i++)phases.push((i/count+(Number(r.id||0)*.618%1)+1)%1);return[{latlngs:ll,bounds:L.latLngBounds(ll),cum:cum,total:total,intensity:intensity,visual:visual(intensity),count:count,speed:52-34*intensity,phases:phases,priority:roadPriority(r)}]}).sort(function(a,b){return b.priority-a.priority});refreshVisible()}
    function refreshVisible(){zoom=map.getZoom();var bounds=map.getBounds().pad(.16),max=zoom<11?24:zoom<13?32:40;visible=prepared.filter(function(r){return bounds.intersects(r.bounds)}).slice(0,max);rebuildTraffic()}
    function pointAt(r,d){var lo=1,hi=r.cum.length-1;while(lo<hi){var mid=Math.floor((lo+hi)/2);if(r.cum[mid]<d)lo=mid+1;else hi=mid}var i=lo;if(i>=r.cum.length)return r.latlngs[r.latlngs.length-1];var seg=r.cum[i]-r.cum[i-1]||1,t=(d-r.cum[i-1])/seg,a=r.latlngs[i-1],b=r.latlngs[i];return L.latLng(a.lat+(b.lat-a.lat)*t,a.lng+(b.lng-a.lng)*t)}
    function waveState(elapsed,center,size){var level=payload.baseLevel?norm(payload.baseLevel):0,seconds=3.2-level*.75,max=Math.hypot(size.x,size.y/.56)*.72,min=Math.max(34,Math.min(size.x,size.y)*.055),span=Math.max(1,max-min),origin=elapsed/seconds%1;return{center:center,phases:[origin,(origin+1/3)%1,(origin+2/3)%1],min:min,span:span,max:max}}
    function waveAt(x,y,w){var dx=x-w.center.x,dy=(y-w.center.y)/.56,dist=Math.hypot(dx,dy),sigma=Math.max(18,w.max*.025),influence=0;w.phases.forEach(function(p){var radius=w.min+p*w.span,delta=dist-radius,hit=Math.exp(-(delta*delta)/(2*sigma*sigma));influence=Math.max(influence,hit*Math.pow(1-p,.28))});return influence}
    function rebuildTraffic(){trafficGroup.clearLayers();trafficDots=[];if(!layers.traffic)return;visible.forEach(function(r){var ratio=zoom<11?.48:zoom<13?.72:1,active=Math.max(2,Math.ceil(r.count*ratio));for(var d=0;d<active;d++){var phase=r.phases[Math.floor(d/active*r.phases.length)]||0,marker=L.circleMarker(r.latlngs[0],{pane:'trafficPane',renderer:trafficRenderer,radius:2,color:r.visual.color,opacity:.28,weight:4,fillColor:r.visual.color,fillOpacity:r.visual.alpha,interactive:false}).addTo(trafficGroup);trafficDots.push({road:r,phase:phase,marker:marker})}})}
    function frame(now){requestAnimationFrame(frame);if(now-lastFrame<1000/12)return;lastFrame=now;if(!layers.traffic||!trafficDots.length)return;var elapsed=(now-started)/1000,size=map.getSize(),scale=Math.min(1.35,Math.max(.82,.92+(zoom-11)*.08)),origin=map.latLngToContainerPoint(L.latLng(CENTER[0],CENTER[1])),wave=waveState(elapsed,origin,size);trafficDots.forEach(function(dot){var r=dot.road,dist=((dot.phase*r.total+elapsed*r.speed)%r.total+r.total)%r.total,ll=pointAt(r,dist),pt=map.latLngToContainerPoint(ll),response=waveAt(pt.x,pt.y,wave),radius=Math.max(1.5,(1.7+r.intensity*.8)*r.visual.scale*scale*(1+response*.42));dot.marker.setLatLng(ll);dot.marker.setRadius(radius)})}
    function resizeMap(){map.invalidateSize({pan:false});refreshVisible()}
    map.on('moveend zoomend',refreshVisible);window.addEventListener('resize',resizeMap);if(window.ResizeObserver)new ResizeObserver(resizeMap).observe(document.getElementById('map-shell'));setTimeout(resizeMap,0);requestAnimationFrame(frame);
    if(window.ReactNativeWebView)window.ReactNativeWebView.postMessage(JSON.stringify({type:'ready'}));
  })();
  </script>
</body>
</html>`;

