export const LIVE_DEMAND_MAP_HTML = String.raw`<!doctype html>
<html lang="pl">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" />
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-pluspuls-map-v1' https://cdn.jsdelivr.net; style-src 'unsafe-inline' https://cdn.jsdelivr.net; img-src data: https://*.basemaps.cartocdn.com; font-src data:; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIINfQ3yn5ccAHs70q7jyhfYwteP4J5i4s=" crossorigin="anonymous" />
  <style>
    :root{color-scheme:dark;--bg:#0a0d14;--surface:rgba(18,22,34,.92);--raised:#1a1f2e;--border:#273044;--text:#eff1f6;--muted:#9298af;--teal:#2ee6a6;--amber:#ffb547;--coral:#ff5470}
    *{box-sizing:border-box}html,body,#map{height:100%;width:100%;margin:0;overflow:hidden;background:var(--bg);font-family:system-ui,-apple-system,"Segoe UI",sans-serif}.leaflet-container{background:#070b11}.leaflet-tile-pane{filter:saturate(.82) contrast(1.12) brightness(.72)}
    #map-shell{position:fixed;inset:0;border:1px solid rgba(46,230,166,.3);overflow:hidden;background:radial-gradient(circle at 50% 52%,rgba(46,230,166,.12),transparent 34rem),linear-gradient(180deg,#080d14,#05080d)}
    #vignette{pointer-events:none;position:absolute;inset:0;z-index:450;background:radial-gradient(circle at 50% 48%,transparent 45%,rgba(4,8,14,.42) 100%)}
    .panel{border:1px solid rgba(46,230,166,.28);background:linear-gradient(180deg,rgba(18,26,37,.94),rgba(10,16,25,.92));box-shadow:0 14px 38px rgba(0,0,0,.55),0 0 22px rgba(46,230,166,.1);backdrop-filter:blur(14px);border-radius:13px;color:var(--text)}
    #title{position:absolute;left:10px;top:10px;z-index:900;padding:9px 11px;display:flex;gap:8px;align-items:center;max-width:185px}.brand{color:var(--teal);font-size:9px;font-weight:900;letter-spacing:.18em;text-transform:uppercase}.subtitle{font-size:10px;color:#c8cedc;margin-top:2px}.navmark{color:var(--teal);font-size:18px;line-height:1}
    #cockpit{position:absolute;right:8px;top:8px;z-index:1000;width:174px;max-height:calc(100% - 16px);overflow:auto;display:flex;flex-direction:column;gap:7px;scrollbar-width:none}#cockpit::-webkit-scrollbar{display:none}.section{padding:9px}.section-head{display:flex;justify-content:space-between;align-items:center;gap:6px;margin-bottom:7px}.section-title{font-size:9px;font-weight:900;letter-spacing:.13em;text-transform:uppercase}.section-meta{font-size:8px;color:var(--muted)}
    .layers{display:grid;grid-template-columns:1fr 1fr;gap:5px}.layer{min-height:42px;text-align:left;border:1px solid rgba(139,143,168,.25);border-radius:9px;background:rgba(16,23,36,.82);color:var(--muted);padding:6px;touch-action:manipulation}.layer.active{border-color:rgba(46,230,166,.58);background:rgba(46,230,166,.14);color:var(--text);box-shadow:0 0 14px rgba(46,230,166,.1)}.layer b{display:block;font-size:9px}.layer small{display:block;font-size:7px;opacity:.72;margin-top:2px}
    .times{display:flex;flex-wrap:wrap;gap:4px}.time{min-width:38px;min-height:32px;border:0;border-radius:8px;background:#141b29;color:var(--muted);font-size:8px;font-weight:900;padding:5px;touch-action:manipulation}.time.active{background:var(--teal);color:#07110e;box-shadow:0 0 15px rgba(46,230,166,.3)}#narrative{font-size:8px;color:var(--muted);line-height:1.35;margin:7px 0 0}.legend{display:flex;flex-wrap:wrap;gap:6px 8px;font-size:7px;color:#dce1eb}.legend span{display:flex;align-items:center;gap:4px}.swatch{width:7px;height:7px;border-radius:50%;display:inline-block}.hex{border-radius:2px}.leaflet-control-attribution{font-size:7px!important;background:rgba(5,8,13,.75)!important;color:#aeb4c4!important}.leaflet-control-attribution a{color:#aeb4c4!important}.leaflet-control-zoom{border:0!important}.leaflet-control-zoom a{background:rgba(18,22,34,.95)!important;color:var(--text)!important;border-color:var(--border)!important}.leaflet-popup-content-wrapper,.leaflet-popup-tip{background:rgba(18,22,34,.98)!important;color:var(--text)!important;border:1px solid rgba(46,230,166,.22)}.leaflet-popup-content{margin:10px 12px;font-size:11px}.route-dash{animation:dash 2s linear infinite;filter:drop-shadow(0 0 3px currentColor)}@keyframes dash{to{stroke-dashoffset:-40}}#sync{position:absolute;left:10px;bottom:10px;z-index:900;padding:7px 9px;font-size:8px;color:var(--muted)}
    @media(max-width:390px){#title{max-width:150px}.subtitle{font-size:8px}#cockpit{width:160px}.section{padding:8px}.layer{padding:5px}.layer small{font-size:6.5px}}
    @media(max-height:590px){#cockpit{width:158px}.layer{min-height:36px}.section{padding:7px}.legend-panel{display:none}}
    @media(prefers-reduced-motion:reduce){.route-dash{animation:none}}
  </style>
  <script src="https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin="anonymous"></script>
</head>
<body>
  <main id="map-shell" aria-label="Interaktywna mapa natężenia ruchu w Krakowie">
    <div id="map"></div><div id="vignette"></div>
    <div id="title" class="panel"><div class="navmark">⌁</div><div><div class="brand">PlusPuls Live</div><div class="subtitle">Kraków demand, routes and traffic</div></div></div>
    <aside id="cockpit" aria-label="Sterowanie mapą">
      <section class="panel section"><div class="section-head"><span class="section-title">Map layers</span><span id="layer-count" class="section-meta">2/5 on</span></div><div class="layers">
        <button class="layer active" data-layer="heatmap" aria-pressed="true"><b>● Heatmap</b><small>hex demand</small></button>
        <button class="layer active" data-layer="traffic" aria-pressed="true"><b>● Signals</b><small>live traffic</small></button>
        <button class="layer" data-layer="points" aria-pressed="false"><b>○ Points</b><small>events & POIs</small></button>
        <button class="layer" data-layer="routes" aria-pressed="false"><b>○ Routes</b><small>best trips</small></button>
        <button class="layer" data-layer="zones" aria-pressed="false"><b>○ Zones</b><small>score labels</small></button>
      </div></section>
      <section class="panel section"><div class="section-head"><span class="section-title">◉ Insight radar</span><span id="target-time" class="section-meta">LIVE</span></div><div class="times">
        <button class="time active" data-hours="0" data-minutes="0">Live</button><button class="time" data-hours="0" data-minutes="30">+30m</button><button class="time" data-hours="1" data-minutes="0">+1h</button><button class="time" data-hours="2" data-minutes="0">+2h</button><button class="time" data-hours="3" data-minutes="0">+3h</button><button class="time" data-hours="6" data-minutes="0">+6h</button><button class="time" data-hours="12" data-minutes="0">+12h</button>
      </div><p id="narrative">Live Kraków traffic and demand intelligence.</p></section>
      <section class="panel section legend-panel"><div class="legend"><span><i class="swatch" style="background:#ff5470"></i>Surge</span><span><i class="swatch" style="background:#2ee6a6"></i>Hot hex</span><span><i class="swatch" style="background:#8b8fa8"></i>Quiet</span><span><i class="swatch" style="background:#2ee6a6"></i>Flow</span><span><i class="swatch" style="background:#ffb547"></i>Heavy</span><span><i class="swatch" style="background:#ff5470"></i>Jam</span></div></section>
    </aside>
    <div id="sync" class="panel">Connecting to PlusPuls signals…</div>
  </main>
  <script nonce="pluspuls-map-v1">
  (function(){
    'use strict';
    var CENTER=[50.0647,19.945], layers={heatmap:true,traffic:true,points:false,routes:false,zones:false};
    var payload={cells:[],roads:[],zones:[],pois:[],routes:[],position:null,narrative:'',targetTime:'LIVE',generatedAt:null,error:null};
    var map=L.map('map',{zoomControl:false,preferCanvas:true,attributionControl:true,minZoom:9,maxZoom:18}).setView(CENTER,12.4);
    L.control.zoom({position:'bottomleft'}).addTo(map);
    L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{subdomains:'abcd',maxZoom:20,attribution:'&copy; OpenStreetMap &copy; CARTO',crossOrigin:true}).addTo(map);
    var heatGroup=L.layerGroup().addTo(map),zoneGroup=L.layerGroup().addTo(map),pointGroup=L.layerGroup().addTo(map),routeGroup=L.layerGroup().addTo(map),driverGroup=L.layerGroup().addTo(map);
    function finite(n){return typeof n==='number'&&isFinite(n)}function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
    function hex(lat,lng,r){var pts=[],mLat=111000,mLng=111000*Math.cos(lat*Math.PI/180);for(var i=0;i<6;i++){var a=i*Math.PI/3;pts.push([lat+r*Math.sin(a)/mLat,lng+r*Math.cos(a)/mLng])}return pts}
    function heatVisual(score){score=clamp(score,0,100);if(score>=90)return['#ff5470',.62];if(score>=75)return['#2ee6a6',.56];if(score>=55)return['#20dfa0',.46];if(score>=35)return['#36f0b7',.32];return['#8b8fa8',.16]}
    function safeText(value){return String(value==null?'':value).slice(0,120)}
    function popup(title,detail){var wrap=document.createElement('div'),strong=document.createElement('strong'),small=document.createElement('div');strong.textContent=safeText(title);small.textContent=safeText(detail);small.style.color='#9298af';small.style.marginTop='4px';wrap.appendChild(strong);wrap.appendChild(small);return wrap}
    function renderHeat(){heatGroup.clearLayers();if(!layers.heatmap||map.getZoom()<11.5)return;(payload.cells||[]).slice(0,700).forEach(function(c){if(!finite(c.lat)||!finite(c.lng)||!finite(c.radius)||!finite(c.score))return;var v=heatVisual(c.score),r=clamp(c.radius,80,1800);L.polygon(hex(c.lat,c.lng,r),{color:v[0],fillColor:v[0],fillOpacity:v[1],weight:1.1,opacity:Math.min(1,v[1]+.25),interactive:false,className:'hex'}).addTo(heatGroup)})}
    function renderZones(){zoneGroup.clearLayers();if(!layers.zones)return;(payload.zones||[]).slice(0,100).forEach(function(z){if(!finite(z.lat)||!finite(z.lng)||!finite(z.radius)||!finite(z.profitScore))return;var v=heatVisual(z.profitScore);L.polygon(hex(z.lat,z.lng,clamp(z.radius*.72,120,2200)),{color:v[0],fillColor:v[0],fillOpacity:Math.max(.14,v[1]*.62),weight:2}).bindPopup(popup(z.zoneName,'Profit score '+Math.round(clamp(z.profitScore,0,100))+'/100')).addTo(zoneGroup)})}
    function renderPoints(){pointGroup.clearLayers();if(!layers.points)return;(payload.pois||[]).slice(0,180).forEach(function(p){if(!finite(p.lat)||!finite(p.lng))return;L.circleMarker([p.lat,p.lng],{radius:5,color:'#7dd3fc',fillColor:'#7dd3fc',fillOpacity:.86,weight:2}).bindPopup(popup(p.name,p.category)).addTo(pointGroup)})}
    function renderRoutes(){routeGroup.clearLayers();if(!layers.routes)return;(payload.routes||[]).slice(0,12).forEach(function(r){var points=(r.geometry||[]).filter(function(p){return Array.isArray(p)&&finite(p[0])&&finite(p[1])}).slice(0,240);if(points.length<2)return;var color=r.role==='drive_to_pickup'?'#7dd3fc':r.role==='nearest_profitable'?'#2ee6a6':'#91f7d7';L.polyline(points,{color:color,weight:7,opacity:.12}).addTo(routeGroup);L.polyline(points,{color:color,weight:r.role==='nearest_profitable'?4:2.5,opacity:.82,dashArray:r.role==='nearest_profitable'?'10 12':'5 12',lineCap:'round',className:'route-dash'}).bindPopup(popup(r.fromShort+' → '+r.toShort,finite(r.estimatedPricePLN)?Math.round(r.estimatedPricePLN)+' PLN':'' )).addTo(routeGroup)})}
    function renderDriver(){driverGroup.clearLayers();var p=payload.position;if(!p||!finite(p.lat)||!finite(p.lng))return;L.circle([p.lat,p.lng],{radius:clamp(p.accuracy||60,20,1000),color:'#2ee6a6',fillColor:'#2ee6a6',fillOpacity:.06,weight:1,dashArray:'4 4'}).addTo(driverGroup);L.circleMarker([p.lat,p.lng],{radius:7,color:'#07110e',fillColor:'#2ee6a6',fillOpacity:1,weight:3}).bindPopup(popup('Twoja lokalizacja','GPS aktywny')).addTo(driverGroup)}
    function renderAll(){renderHeat();renderZones();renderPoints();renderRoutes();renderDriver();prepareRoads();document.getElementById('narrative').textContent=safeText(payload.narrative||'Live Kraków traffic and demand intelligence.');document.getElementById('target-time').textContent=safeText(payload.targetTime||'LIVE');var sync=document.getElementById('sync');sync.textContent=payload.error?safeText(payload.error):((payload.roads||[]).length+' roads · '+(payload.cells||[]).length+' heat cells · live');sync.style.color=payload.error?'#ffb547':'#9298af'}
    map.on('zoomend',function(){renderHeat();refreshVisible()});
    document.querySelectorAll('.layer').forEach(function(btn){btn.addEventListener('click',function(){var id=btn.getAttribute('data-layer');layers[id]=!layers[id];btn.classList.toggle('active',layers[id]);btn.setAttribute('aria-pressed',String(layers[id]));var b=btn.querySelector('b');if(b)b.textContent=(layers[id]?'● ':'○ ')+({heatmap:'Heatmap',traffic:'Signals',points:'Points',routes:'Routes',zones:'Zones'}[id]||id);document.getElementById('layer-count').textContent=Object.keys(layers).filter(function(k){return layers[k]}).length+'/5 on';renderAll()})});
    document.querySelectorAll('.time').forEach(function(btn){btn.addEventListener('click',function(){document.querySelectorAll('.time').forEach(function(b){b.classList.remove('active')});btn.classList.add('active');var h=Number(btn.getAttribute('data-hours')),m=Number(btn.getAttribute('data-minutes'));if(window.ReactNativeWebView)window.ReactNativeWebView.postMessage(JSON.stringify({type:'time',hours:h,minutes:m,label:btn.textContent}))})});
    function receive(event){try{var data=JSON.parse(event.data);if(data&&data.type==='map-data'){payload=data.payload||payload;renderAll()}}catch(_){}}
    window.addEventListener('message',receive);document.addEventListener('message',receive);

    var canvas=document.createElement('canvas');canvas.style.cssText='position:absolute;inset:0;pointer-events:none;z-index:430';map.getContainer().appendChild(canvas);var ctx=canvas.getContext('2d'),dpr=Math.min(window.devicePixelRatio||1,1.75),prepared=[],visible=[],zoom=map.getZoom(),started=performance.now(),lastFrame=0;
    function resize(){var s=map.getSize();canvas.width=Math.max(1,Math.floor(s.x*dpr));canvas.height=Math.max(1,Math.floor(s.y*dpr));canvas.style.width=s.x+'px';canvas.style.height=s.y+'px'}
    function norm(v){return finite(v)?clamp(v,0,1):0}function roadPriority(r){var p={motorway:5,trunk:4,primary:3,secondary:2,tertiary:1};return(p[r.highway]||0)*10+norm(r.intensity)*12}
    function visual(i){return i>=.7?{color:'#ff5470',alpha:.98,scale:1.18}:i>=.42?{color:'#ffb547',alpha:.94,scale:1.08}:{color:'#2ee6a6',alpha:.9,scale:1}}
    function prepareRoads(){prepared=(payload.roads||[]).slice(0,180).flatMap(function(r){var ll=(r.geometry||[]).filter(function(p){return Array.isArray(p)&&finite(p[0])&&finite(p[1])}).slice(0,180).map(function(p){return L.latLng(p[0],p[1])});if(ll.length<2)return[];var cum=[0];for(var i=1;i<ll.length;i++)cum.push(cum[i-1]+ll[i-1].distanceTo(ll[i]));var total=cum[cum.length-1];if(total<50)return[];var intensity=norm(r.intensity),count=Math.min(32,Math.max(2,Math.round(total/200*(.68+intensity*.82)))),phases=[];for(i=0;i<count;i++)phases.push((i/count+(Number(r.id||0)*.618%1)+1)%1);return[{latlngs:ll,bounds:L.latLngBounds(ll),cum:cum,total:total,intensity:intensity,visual:visual(intensity),count:count,speed:52-34*intensity,phases:phases,priority:roadPriority(r)}]}).sort(function(a,b){return b.priority-a.priority});refreshVisible()}
    function refreshVisible(){zoom=map.getZoom();var bounds=map.getBounds().pad(.1),max=zoom<11?38:zoom<12.5?62:100;visible=prepared.filter(function(r){return bounds.intersects(r.bounds)}).slice(0,Math.min(max,44))}
    function pointAt(r,d){var lo=1,hi=r.cum.length-1;while(lo<hi){var mid=Math.floor((lo+hi)/2);if(r.cum[mid]<d)lo=mid+1;else hi=mid}var i=lo;if(i>=r.cum.length)return r.latlngs[r.latlngs.length-1];var seg=r.cum[i]-r.cum[i-1]||1,t=(d-r.cum[i-1])/seg,a=r.latlngs[i-1],b=r.latlngs[i];return L.latLng(a.lat+(b.lat-a.lat)*t,a.lng+(b.lng-a.lng)*t)}
    function waveState(elapsed,center,size){var level=payload.baseLevel?norm(payload.baseLevel):0,seconds=3.2-level*.75,max=Math.hypot(size.x,size.y/.56)*.72,min=Math.max(34,Math.min(size.x,size.y)*.055),span=Math.max(1,max-min),origin=elapsed/seconds%1;return{center:center,phases:[origin,(origin+1/3)%1,(origin+2/3)%1],min:min,span:span,max:max}}
    function waveAt(x,y,w){var dx=x-w.center.x,dy=(y-w.center.y)/.56,dist=Math.hypot(dx,dy),sigma=Math.max(18,w.max*.025),influence=0;w.phases.forEach(function(p){var radius=w.min+p*w.span,delta=dist-radius,hit=Math.exp(-(delta*delta)/(2*sigma*sigma));influence=Math.max(influence,hit*Math.pow(1-p,.28))});return influence}
    function frame(now){requestAnimationFrame(frame);if(now-lastFrame<1000/24)return;lastFrame=now;var elapsed=(now-started)/1000,size=map.getSize();ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,size.x,size.y);if(!layers.traffic)return;var scale=Math.min(1.38,Math.max(.62,.76+(zoom-11)*.1)),origin=map.latLngToContainerPoint(L.latLng(CENTER[0],CENTER[1])),wave=waveState(elapsed,origin,size);['#2ee6a6','#ffb547','#ff5470'].forEach(function(color){var dots=[];visible.forEach(function(r){if(r.visual.color!==color)return;var ratio=zoom<11?.52:zoom<12?.76:1,active=Math.max(2,Math.ceil(r.count*ratio));for(var d=0;d<active;d++){var phase=r.phases[Math.floor(d/active*r.phases.length)]||0,dist=((phase*r.total+elapsed*r.speed)%r.total+r.total)%r.total,ll=pointAt(r,dist),pt=map.latLngToContainerPoint(ll);if(pt.x<-34||pt.y<-34||pt.x>size.x+34||pt.y>size.y+34)continue;var response=waveAt(pt.x,pt.y,wave),radius=Math.max(.72,(.92+r.intensity*.66)*r.visual.scale*scale);dots.push({x:pt.x,y:pt.y,r:radius,a:r.visual.alpha,w:response})}});if(!dots.length)return;ctx.save();ctx.globalCompositeOperation='lighter';ctx.fillStyle=color;ctx.globalAlpha=.11;ctx.beginPath();dots.forEach(function(d){var h=d.r*(2.15+d.w*2.15);ctx.moveTo(d.x+h,d.y);ctx.arc(d.x,d.y,h,0,Math.PI*2)});ctx.fill();ctx.restore();ctx.save();ctx.fillStyle=color;ctx.globalAlpha=Math.min(.99,dots.reduce(function(s,d){return s+d.a},0)/dots.length);ctx.beginPath();dots.forEach(function(d){var c=d.r*(.94+d.w*.42);ctx.moveTo(d.x+c,d.y);ctx.arc(d.x,d.y,c,0,Math.PI*2)});ctx.fill();ctx.restore();ctx.save();ctx.fillStyle='rgba(255,255,255,.92)';ctx.globalAlpha=.58;ctx.beginPath();dots.forEach(function(d){var h=Math.max(.34,d.r*(.24+d.w*.05));ctx.moveTo(d.x+h,d.y);ctx.arc(d.x,d.y,h,0,Math.PI*2)});ctx.fill();ctx.restore()})}
    resize();refreshVisible();map.on('resize',resize);map.on('move zoom moveend zoomend',refreshVisible);requestAnimationFrame(frame);
    if(window.ReactNativeWebView)window.ReactNativeWebView.postMessage(JSON.stringify({type:'ready'}));
  })();
  </script>
</body>
</html>`;
