import { useEffect, useMemo, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { fetchRoadTraffic, type RoadSegment, type RoadTrafficResponse } from "@/lib/api";
import { theme } from "@/lib/theme";

type Point={x:number;y:number};
type PreparedRoad={id:number;intensity:number;points:Point[];cumulative:number[];total:number;dotCount:number;phaseSeed:number};
function clamp(v:number){return Number.isFinite(v)?Math.max(0,Math.min(1,v)):0}
function color(v:number){return v>=.72?theme.danger:v>=.48?theme.warning:theme.primary}
function priority(r:RoadSegment){const p:Record<string,number>={motorway:5,trunk:4,primary:3,secondary:2,tertiary:1};return(p[r.highway]??0)*10+clamp(r.intensity)*12}
function pointAt(r:PreparedRoad,d:number):Point{const w=((d%r.total)+r.total)%r.total;let i=1;while(i<r.cumulative.length&&r.cumulative[i]!<w)i++;if(i>=r.points.length)return r.points[r.points.length-1]!;const before=r.cumulative[i-1]??0;const seg=Math.max(r.cumulative[i]!-before,.000001);const t=(w-before)/seg;const a=r.points[i-1]!,b=r.points[i]!;return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}}
export function TrafficPulseField({enabled=true}:{enabled?:boolean}){
 const[data,setData]=useState<RoadTrafficResponse|null>(null);const[tick,setTick]=useState(0);const[size,setSize]=useState({width:0,height:0});
 useEffect(()=>{if(!enabled)return;let active=true;const load=async()=>{try{const next=await fetchRoadTraffic();if(active)setData(next)}catch{}};void load();const poll=setInterval(()=>void load(),15000);return()=>{active=false;clearInterval(poll)}},[enabled]);
 useEffect(()=>{if(!enabled)return;const started=Date.now();const timer=setInterval(()=>setTick((Date.now()-started)/1000),100);return()=>clearInterval(timer)},[enabled]);
 const roads=useMemo<PreparedRoad[]>(()=>{const source=data?.roads.filter(r=>r.geometry.length>=2).sort((a,b)=>priority(b)-priority(a)).slice(0,38)??[];if(!source.length)return[];const all=source.flatMap(r=>r.geometry),minLat=Math.min(...all.map(p=>p[0])),maxLat=Math.max(...all.map(p=>p[0])),minLng=Math.min(...all.map(p=>p[1])),maxLng=Math.max(...all.map(p=>p[1])),latSpan=Math.max(maxLat-minLat,.0001),lngSpan=Math.max(maxLng-minLng,.0001);return source.flatMap(r=>{const step=Math.max(1,Math.ceil(r.geometry.length/16));const sample=r.geometry.filter((_,i)=>i%step===0);const last=r.geometry[r.geometry.length-1]!;if(sample[sample.length-1]!==last)sample.push(last);const points=sample.map(([lat,lng])=>({x:.04+(lng-minLng)/lngSpan*.92,y:.04+(1-(lat-minLat)/latSpan)*.92}));const cumulative=[0];for(let i=1;i<points.length;i++){const a=points[i-1]!,b=points[i]!;cumulative.push(cumulative[i-1]!+Math.hypot(b.x-a.x,b.y-a.y))}const total=cumulative[cumulative.length-1]??0;if(total<.005)return[];const intensity=clamp(r.intensity);return[{id:r.id,intensity,points,cumulative,total,dotCount:Math.max(2,Math.min(7,Math.round(2+intensity*5+total*4))),phaseSeed:(r.id*.61803398875)%1}]})},[data]);
 if(!enabled)return null;
 return <View style={s.field} onLayout={e=>setSize(e.nativeEvent.layout)} pointerEvents="none"><View style={s.grid}/>{size.width>0&&size.height>0?roads.flatMap(r=>{const c=color(r.intensity),speed=.035+(1-r.intensity)*.055;return Array.from({length:r.dotCount},(_,i)=>{const phase=(i/r.dotCount+r.phaseSeed+tick*speed)%1,p=pointAt(r,phase*r.total),radius=2.2+r.intensity*2.6+((Math.sin(tick*4.2+phase*Math.PI*2)+1)/2)*1.1;return <View key={`${r.id}-${i}`} style={[s.dot,{left:p.x*size.width-radius,top:p.y*size.height-radius,width:radius*2,height:radius*2,borderRadius:radius,backgroundColor:c,shadowColor:c}]}/>})}):null}<View style={s.legend}><View style={s.live}><View style={s.liveDot}/><Text style={s.title}>LIVE ROAD FLOW</Text></View><Text style={s.meta}>{data?`${data.roads.length} dróg · ${String(data.hour).padStart(2,"0")}:00`:"Łączenie z ruchem Krakowa…"}</Text><Text style={s.scale}>● płynnie   ● wolno   ● korek</Text></View></View>
}
const s=StyleSheet.create({field:{...StyleSheet.absoluteFill,overflow:"hidden",backgroundColor:"#0B1117"},grid:{position:"absolute",left:"8%",right:"8%",top:"14%",bottom:"10%",borderWidth:1,borderColor:"rgba(139,143,168,0.08)",borderRadius:26},dot:{position:"absolute",elevation:5,shadowOpacity:.95,shadowRadius:7},legend:{position:"absolute",left:12,top:12,paddingHorizontal:11,paddingVertical:9,borderRadius:12,backgroundColor:"rgba(10,13,20,0.84)",borderWidth:1,borderColor:"rgba(46,230,166,0.2)"},live:{flexDirection:"row",alignItems:"center",gap:6},liveDot:{width:6,height:6,borderRadius:3,backgroundColor:theme.primary},title:{color:theme.primary,fontSize:9,fontWeight:"900",letterSpacing:1},meta:{color:theme.muted,fontSize:9,marginTop:3},scale:{color:theme.muted,fontSize:8,marginTop:6}});
