import type {
  ShiftPhase,
  MacroZone,
  MicroZone,
  LoopDefinition,
  TrapDefinition,
  CopilotAction,
  RideOffer,
  RideScoreLabel,
} from "../shared/copilot";
import { ACTION_COOLDOWNS } from "../shared/copilot";

export const SHIFT_PHASES: ShiftPhase[] = [
  {
    id: "early_morning",
    name: "early_morning",
    displayName: "Early Morning",
    timeRange: [5, 7],
    description: "Airport transfers and early commuters. Low competition, steady airport demand.",
    demandPattern: "Airport-driven with scattered commuter pickups",
    optimalZoneTypes: ["airport_feeder", "hotel_district", "residential"],
    color: "#6366F1",
    earningsPotentialLabel: "moderate",
  },
  {
    id: "morning_rush",
    name: "morning_rush",
    displayName: "Morning Rush",
    timeRange: [7, 10],
    description: "Peak commuter demand. Business districts and train station active.",
    demandPattern: "Concentrated around transit hubs and business areas",
    optimalZoneTypes: ["train_station", "business", "residential"],
    color: "#F59E0B",
    earningsPotentialLabel: "high",
  },
  {
    id: "midday",
    name: "midday",
    displayName: "Midday",
    timeRange: [10, 13],
    description: "Tourist activity picks up. Shopping and sightseeing rides.",
    demandPattern: "Tourist corridors and shopping areas with moderate spread",
    optimalZoneTypes: ["tourist", "shopping", "old_town"],
    color: "#10B981",
    earningsPotentialLabel: "moderate",
  },
  {
    id: "afternoon",
    name: "afternoon",
    displayName: "Afternoon",
    timeRange: [13, 16],
    description: "Steady mixed demand. Business meetings, tourist movement, early school pickups.",
    demandPattern: "Distributed across business and tourist zones",
    optimalZoneTypes: ["business", "tourist", "university"],
    color: "#3B82F6",
    earningsPotentialLabel: "moderate",
  },
  {
    id: "evening_rush",
    name: "evening_rush",
    displayName: "Evening Rush",
    timeRange: [16, 19],
    description: "Peak demand period. Workers heading home, event pre-positioning opportunity.",
    demandPattern: "Strong outbound from business districts, event venues loading",
    optimalZoneTypes: ["business", "train_station", "event_venue"],
    color: "#EF4444",
    earningsPotentialLabel: "high",
  },
  {
    id: "evening",
    name: "evening",
    displayName: "Evening",
    timeRange: [19, 22],
    description: "Restaurant and entertainment demand. Event exits create surge windows.",
    demandPattern: "Nightlife districts and event venue exits",
    optimalZoneTypes: ["nightlife", "restaurant", "event_venue"],
    color: "#8B5CF6",
    earningsPotentialLabel: "high",
  },
  {
    id: "late_night",
    name: "late_night",
    displayName: "Late Night",
    timeRange: [22, 1],
    description: "Club and bar exits. High per-ride value but longer idle between rides.",
    demandPattern: "Concentrated around nightlife with suburban dropoffs",
    optimalZoneTypes: ["nightlife", "old_town", "club_district"],
    color: "#EC4899",
    earningsPotentialLabel: "high",
  },
  {
    id: "overnight",
    name: "overnight",
    displayName: "Overnight",
    timeRange: [1, 5],
    description: "Minimal demand. Airport early flights and last nightlife stragglers.",
    demandPattern: "Sparse, airport-oriented toward 4am",
    optimalZoneTypes: ["airport_feeder", "nightlife"],
    color: "#6B7280",
    earningsPotentialLabel: "low",
  },
];

export const MACRO_ZONES: MacroZone[] = [
  { id: "old_town", name: "Old Town (Stare Miasto)", description: "Historic center including Rynek G\u0142\u00f3wny, tourist heart of Krak\u00f3w" },
  { id: "kazimierz", name: "Kazimierz", description: "Jewish quarter, nightlife hub, restaurants and bars" },
  { id: "podgorze", name: "Podg\u00f3rze", description: "South bank district, Schindler's Factory area, growing residential" },
  { id: "nowa_huta", name: "Nowa Huta", description: "Eastern district, socialist-era planned town, residential" },
  { id: "krowodrza", name: "Krowodrza", description: "Northwest district, university area, residential mix" },
  { id: "zablocie", name: "Zab\u0142ocie", description: "Revitalized industrial area, creative offices and lofts" },
  { id: "airport_zone", name: "Airport Zone (Balice)", description: "KRK airport area and approach corridors" },
  { id: "bronowice", name: "Bronowice", description: "Western residential, Galeria Bronowice shopping" },
  { id: "pradnik", name: "Pr\u0105dnik", description: "Northern residential districts, hospitals" },
  { id: "debniki", name: "D\u0119bniki", description: "Southwest residential, close to Wawel, mixed use" },
  { id: "zwierzyniec", name: "Zwierzyniec", description: "Western green belt, Kosciuszko Mound, affluent residential" },
  { id: "wieliczka_corridor", name: "Wieliczka Corridor", description: "Southeast corridor toward Wieliczka Salt Mine, suburban" },
];

export const MICRO_ZONES: MicroZone[] = [
  {
    id: "rynek_glowny",
    name: "Rynek G\u0142\u00f3wny",
    lat: 50.0614,
    lng: 19.9372,
    macroZoneId: "old_town",
    bestPhases: ["midday", "afternoon", "evening"],
    weekdayDemandByHour: [1, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 7, 6, 5, 5, 6, 7, 8, 8, 7, 6, 5, 3],
    weekendDemandByHour: [2, 1, 1, 0, 0, 0, 1, 2, 3, 5, 7, 8, 8, 8, 7, 6, 6, 7, 9, 9, 8, 7, 6, 4],
    oversupplyRisk: "high",
    likelyDirection: "Kazimierz or station",
    avgTripLengthKm: 3.2,
    idleRiskMinutes: 12,
    rainMultiplier: 1.8,
    eventSensitivity: 0.9,
    airportSensitivity: 0.2,
    notes: "Tourist magnet. High oversupply from idle drivers. Better to cruise through than wait.",
  },
  {
    id: "kazimierz_center",
    name: "Kazimierz Center",
    lat: 50.0512,
    lng: 19.9448,
    macroZoneId: "kazimierz",
    bestPhases: ["evening", "late_night"],
    weekdayDemandByHour: [2, 1, 0, 0, 0, 0, 1, 2, 3, 3, 4, 5, 5, 5, 4, 4, 5, 6, 7, 8, 8, 7, 6, 4],
    weekendDemandByHour: [3, 2, 1, 1, 0, 0, 0, 1, 2, 4, 5, 6, 6, 6, 5, 5, 6, 7, 9, 10, 9, 8, 7, 5],
    oversupplyRisk: "medium",
    likelyDirection: "Old Town, Podg\u00f3rze, or suburbs",
    avgTripLengthKm: 4.1,
    idleRiskMinutes: 8,
    rainMultiplier: 1.5,
    eventSensitivity: 0.7,
    airportSensitivity: 0.1,
    notes: "Strong evening/night zone. Restaurants fill before nightlife kicks in.",
  },
  {
    id: "krakow_glowny",
    name: "Krak\u00f3w G\u0142\u00f3wny Station",
    lat: 50.0681,
    lng: 19.9467,
    macroZoneId: "old_town",
    bestPhases: ["morning_rush", "afternoon", "evening_rush"],
    weekdayDemandByHour: [1, 0, 0, 0, 1, 3, 5, 8, 9, 7, 5, 4, 4, 5, 6, 7, 8, 9, 8, 6, 5, 4, 3, 2],
    weekendDemandByHour: [1, 1, 0, 0, 0, 2, 3, 5, 6, 7, 6, 5, 5, 5, 6, 7, 7, 8, 7, 6, 5, 4, 3, 2],
    oversupplyRisk: "high",
    likelyDirection: "Hotels, Old Town, or suburbs",
    avgTripLengthKm: 5.8,
    idleRiskMinutes: 10,
    rainMultiplier: 1.6,
    eventSensitivity: 0.4,
    airportSensitivity: 0.3,
    notes: "Major transit hub. Train arrivals create waves. Queue can be long.",
  },
  {
    id: "galeria_krakowska",
    name: "Galeria Krakowska",
    lat: 50.0678,
    lng: 19.9450,
    macroZoneId: "old_town",
    bestPhases: ["midday", "afternoon", "evening_rush"],
    weekdayDemandByHour: [0, 0, 0, 0, 0, 0, 1, 2, 3, 5, 7, 7, 6, 6, 6, 6, 7, 8, 7, 5, 4, 2, 1, 0],
    weekendDemandByHour: [0, 0, 0, 0, 0, 0, 0, 1, 2, 5, 8, 8, 8, 7, 7, 7, 7, 8, 7, 5, 3, 2, 1, 0],
    oversupplyRisk: "medium",
    likelyDirection: "Suburbs and residential",
    avgTripLengthKm: 6.2,
    idleRiskMinutes: 9,
    rainMultiplier: 1.4,
    eventSensitivity: 0.3,
    airportSensitivity: 0.2,
    notes: "Shopping mall adjacent to station. Good suburban rides after 17:00.",
  },
  {
    id: "airport_krk",
    name: "KRK Airport (Balice)",
    lat: 50.0777,
    lng: 19.7848,
    macroZoneId: "airport_zone",
    bestPhases: ["early_morning", "morning_rush", "evening"],
    weekdayDemandByHour: [1, 0, 0, 0, 2, 4, 5, 6, 7, 8, 7, 6, 5, 5, 5, 5, 6, 7, 7, 6, 5, 4, 3, 2],
    weekendDemandByHour: [1, 0, 0, 0, 1, 3, 4, 5, 6, 7, 8, 8, 7, 6, 5, 5, 5, 6, 7, 7, 6, 5, 4, 2],
    oversupplyRisk: "high",
    likelyDirection: "City center or hotels",
    avgTripLengthKm: 14.5,
    idleRiskMinutes: 18,
    rainMultiplier: 1.0,
    eventSensitivity: 0.1,
    airportSensitivity: 1.0,
    notes: "High-value rides but blind queue risk. Time to arrival wave matters most.",
  },
  {
    id: "airport_feeder",
    name: "Airport Feeder (Balice Road)",
    lat: 50.0750,
    lng: 19.8200,
    macroZoneId: "airport_zone",
    bestPhases: ["early_morning", "morning_rush"],
    weekdayDemandByHour: [1, 0, 0, 0, 2, 3, 4, 5, 5, 4, 3, 2, 2, 2, 2, 3, 3, 4, 4, 3, 2, 2, 1, 1],
    weekendDemandByHour: [1, 0, 0, 0, 1, 2, 3, 4, 4, 4, 3, 3, 3, 2, 2, 2, 3, 3, 4, 3, 3, 2, 1, 1],
    oversupplyRisk: "low",
    likelyDirection: "Airport or city center",
    avgTripLengthKm: 10.0,
    idleRiskMinutes: 6,
    rainMultiplier: 1.1,
    eventSensitivity: 0.1,
    airportSensitivity: 0.8,
    notes: "Position here before flight waves instead of queuing at terminal.",
  },
  {
    id: "wawel_area",
    name: "Wawel Castle Area",
    lat: 50.0540,
    lng: 19.9352,
    macroZoneId: "old_town",
    bestPhases: ["midday", "afternoon"],
    weekdayDemandByHour: [0, 0, 0, 0, 0, 0, 1, 2, 3, 5, 6, 7, 7, 6, 5, 5, 5, 5, 4, 3, 2, 1, 0, 0],
    weekendDemandByHour: [0, 0, 0, 0, 0, 0, 0, 1, 3, 6, 7, 8, 8, 7, 6, 6, 5, 5, 4, 3, 2, 1, 0, 0],
    oversupplyRisk: "medium",
    likelyDirection: "Kazimierz or Old Town",
    avgTripLengthKm: 3.0,
    idleRiskMinutes: 10,
    rainMultiplier: 1.7,
    eventSensitivity: 0.5,
    airportSensitivity: 0.1,
    notes: "Tourist rides, often short. Good chaining with Kazimierz.",
  },
  {
    id: "podgorze_center",
    name: "Podg\u00f3rze Center",
    lat: 50.0440,
    lng: 19.9500,
    macroZoneId: "podgorze",
    bestPhases: ["morning_rush", "evening_rush"],
    weekdayDemandByHour: [0, 0, 0, 0, 0, 1, 3, 5, 6, 5, 3, 3, 3, 3, 3, 4, 5, 6, 5, 4, 3, 2, 1, 0],
    weekendDemandByHour: [0, 0, 0, 0, 0, 0, 1, 3, 4, 4, 4, 4, 4, 4, 3, 3, 4, 5, 5, 4, 3, 2, 1, 0],
    oversupplyRisk: "low",
    likelyDirection: "City center or Kazimierz",
    avgTripLengthKm: 4.5,
    idleRiskMinutes: 7,
    rainMultiplier: 1.3,
    eventSensitivity: 0.3,
    airportSensitivity: 0.1,
    notes: "Residential outbound mornings, inbound evenings. Schindler's Factory tourist traffic midday.",
  },
  {
    id: "zablocie_hub",
    name: "Zab\u0142ocie Creative Hub",
    lat: 50.0470,
    lng: 19.9580,
    macroZoneId: "zablocie",
    bestPhases: ["morning_rush", "evening_rush"],
    weekdayDemandByHour: [0, 0, 0, 0, 0, 1, 2, 5, 6, 5, 4, 3, 3, 3, 3, 4, 5, 7, 6, 4, 3, 2, 1, 0],
    weekendDemandByHour: [0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 4, 4, 4, 4, 3, 3, 4, 5, 5, 4, 3, 2, 1, 0],
    oversupplyRisk: "low",
    likelyDirection: "Old Town or station",
    avgTripLengthKm: 3.8,
    idleRiskMinutes: 6,
    rainMultiplier: 1.3,
    eventSensitivity: 0.4,
    airportSensitivity: 0.1,
    notes: "Tech offices generate consistent commuter rides. Low competition.",
  },
  {
    id: "nowa_huta_centrum",
    name: "Nowa Huta Centrum",
    lat: 50.0725,
    lng: 20.0380,
    macroZoneId: "nowa_huta",
    bestPhases: ["morning_rush", "evening_rush"],
    weekdayDemandByHour: [0, 0, 0, 0, 0, 2, 4, 6, 5, 3, 2, 2, 2, 2, 2, 3, 5, 6, 4, 3, 2, 1, 0, 0],
    weekendDemandByHour: [0, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3, 3, 3, 3, 2, 2, 3, 4, 3, 3, 2, 1, 0, 0],
    oversupplyRisk: "low",
    likelyDirection: "City center",
    avgTripLengthKm: 8.5,
    idleRiskMinutes: 11,
    rainMultiplier: 1.2,
    eventSensitivity: 0.1,
    airportSensitivity: 0.1,
    notes: "Long rides to center but high idle risk after. Morning commute is strongest.",
  },
  {
    id: "bronowice_mall",
    name: "Galeria Bronowice",
    lat: 50.0830,
    lng: 19.8900,
    macroZoneId: "bronowice",
    bestPhases: ["midday", "afternoon", "evening_rush"],
    weekdayDemandByHour: [0, 0, 0, 0, 0, 0, 0, 1, 2, 4, 6, 6, 5, 5, 5, 5, 6, 7, 6, 4, 3, 2, 0, 0],
    weekendDemandByHour: [0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 7, 7, 7, 6, 6, 6, 6, 7, 6, 4, 3, 1, 0, 0],
    oversupplyRisk: "medium",
    likelyDirection: "Western suburbs or center",
    avgTripLengthKm: 5.5,
    idleRiskMinutes: 9,
    rainMultiplier: 1.3,
    eventSensitivity: 0.2,
    airportSensitivity: 0.3,
    notes: "Shopping traffic. Suburban rides tend to be medium-distance. Mall parking queue risk.",
  },
  {
    id: "tauron_arena",
    name: "Tauron Arena",
    lat: 50.0692,
    lng: 20.0108,
    macroZoneId: "nowa_huta",
    bestPhases: ["evening", "late_night"],
    weekdayDemandByHour: [0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 4, 5, 7, 8, 6, 3, 1],
    weekendDemandByHour: [0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3, 3, 4, 5, 6, 7, 9, 9, 7, 4, 2],
    oversupplyRisk: "medium",
    likelyDirection: "City center or station",
    avgTripLengthKm: 6.0,
    idleRiskMinutes: 7,
    rainMultiplier: 1.1,
    eventSensitivity: 1.0,
    airportSensitivity: 0.0,
    notes: "Event-dependent. Massive surge at event end. Pre-position 15min before end.",
  },
  {
    id: "icekrakow",
    name: "ICE Krak\u00f3w Congress Centre",
    lat: 50.0518,
    lng: 19.9290,
    macroZoneId: "debniki",
    bestPhases: ["afternoon", "evening"],
    weekdayDemandByHour: [0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3, 4, 4, 4, 5, 6, 7, 6, 4, 3, 1, 0],
    weekendDemandByHour: [0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 4, 4, 4, 4, 5, 6, 7, 7, 5, 3, 1, 0],
    oversupplyRisk: "low",
    likelyDirection: "Hotels, Old Town, or station",
    avgTripLengthKm: 4.2,
    idleRiskMinutes: 8,
    rainMultiplier: 1.2,
    eventSensitivity: 0.9,
    airportSensitivity: 0.1,
    notes: "Conference and congress venue. Business travelers tip well. Event schedule drives demand.",
  },
  {
    id: "debniki_residential",
    name: "D\u0119bniki Residential",
    lat: 50.0460,
    lng: 19.9200,
    macroZoneId: "debniki",
    bestPhases: ["morning_rush", "evening_rush"],
    weekdayDemandByHour: [0, 0, 0, 0, 0, 1, 3, 5, 6, 4, 3, 2, 2, 2, 2, 3, 5, 6, 5, 3, 2, 1, 0, 0],
    weekendDemandByHour: [0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3, 3, 3, 2, 2, 3, 4, 4, 3, 2, 1, 0, 0],
    oversupplyRisk: "low",
    likelyDirection: "Center or Wawel area",
    avgTripLengthKm: 3.5,
    idleRiskMinutes: 8,
    rainMultiplier: 1.4,
    eventSensitivity: 0.2,
    airportSensitivity: 0.1,
    notes: "Residential commuter zone. Outbound mornings, inbound evenings.",
  },
  {
    id: "pradnik_bialy",
    name: "Pr\u0105dnik Bia\u0142y",
    lat: 50.0960,
    lng: 19.9280,
    macroZoneId: "pradnik",
    bestPhases: ["morning_rush"],
    weekdayDemandByHour: [0, 0, 0, 0, 0, 2, 4, 6, 5, 3, 2, 2, 2, 2, 2, 3, 4, 5, 4, 3, 2, 1, 0, 0],
    weekendDemandByHour: [0, 0, 0, 0, 0, 1, 2, 3, 3, 3, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2, 2, 1, 0, 0],
    oversupplyRisk: "low",
    likelyDirection: "City center",
    avgTripLengthKm: 6.0,
    idleRiskMinutes: 12,
    rainMultiplier: 1.3,
    eventSensitivity: 0.1,
    airportSensitivity: 0.1,
    notes: "Northern suburb. One-way commuter rides. High idle risk after drop-off in center.",
  },
  {
    id: "krowodrza_gorka",
    name: "Krowodrza G\u00f3rka",
    lat: 50.0850,
    lng: 19.9100,
    macroZoneId: "krowodrza",
    bestPhases: ["morning_rush", "evening_rush"],
    weekdayDemandByHour: [0, 0, 0, 0, 0, 1, 3, 5, 5, 4, 3, 2, 2, 2, 2, 3, 5, 5, 4, 3, 2, 1, 0, 0],
    weekendDemandByHour: [0, 0, 0, 0, 0, 0, 1, 3, 3, 3, 3, 3, 3, 3, 2, 2, 3, 4, 3, 3, 2, 1, 0, 0],
    oversupplyRisk: "low",
    likelyDirection: "City center or university",
    avgTripLengthKm: 4.8,
    idleRiskMinutes: 10,
    rainMultiplier: 1.3,
    eventSensitivity: 0.1,
    airportSensitivity: 0.2,
    notes: "Residential area with university proximity. Consistent morning commuter demand.",
  },
  {
    id: "plaszow",
    name: "P\u0142asz\u00f3w",
    lat: 50.0370,
    lng: 19.9650,
    macroZoneId: "podgorze",
    bestPhases: ["morning_rush", "evening_rush"],
    weekdayDemandByHour: [0, 0, 0, 0, 0, 1, 3, 5, 5, 4, 2, 2, 2, 2, 2, 3, 5, 5, 4, 3, 2, 1, 0, 0],
    weekendDemandByHour: [0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2, 2, 1, 0, 0],
    oversupplyRisk: "low",
    likelyDirection: "City center or Kazimierz",
    avgTripLengthKm: 5.5,
    idleRiskMinutes: 10,
    rainMultiplier: 1.2,
    eventSensitivity: 0.2,
    airportSensitivity: 0.1,
    notes: "Southern residential. P\u0142asz\u00f3w station provides some transit-related demand.",
  },
  {
    id: "zwierzyniec_west",
    name: "Zwierzyniec West",
    lat: 50.0580,
    lng: 19.8950,
    macroZoneId: "zwierzyniec",
    bestPhases: ["morning_rush"],
    weekdayDemandByHour: [0, 0, 0, 0, 0, 1, 2, 4, 4, 3, 2, 2, 2, 2, 2, 2, 3, 4, 3, 2, 1, 1, 0, 0],
    weekendDemandByHour: [0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3, 3, 3, 2, 2, 2, 3, 3, 2, 2, 1, 0, 0],
    oversupplyRisk: "low",
    likelyDirection: "City center",
    avgTripLengthKm: 4.0,
    idleRiskMinutes: 13,
    rainMultiplier: 1.4,
    eventSensitivity: 0.1,
    airportSensitivity: 0.3,
    notes: "Affluent area, good tips. But high idle risk due to sparse demand outside rush.",
  },
  {
    id: "wieliczka_salt_mine",
    name: "Wieliczka Salt Mine",
    lat: 49.9833,
    lng: 20.0556,
    macroZoneId: "wieliczka_corridor",
    bestPhases: ["midday", "afternoon"],
    weekdayDemandByHour: [0, 0, 0, 0, 0, 0, 0, 1, 2, 4, 5, 6, 6, 6, 5, 5, 4, 3, 2, 1, 0, 0, 0, 0],
    weekendDemandByHour: [0, 0, 0, 0, 0, 0, 0, 0, 2, 5, 7, 8, 8, 7, 6, 6, 5, 4, 2, 1, 0, 0, 0, 0],
    oversupplyRisk: "medium",
    likelyDirection: "Krak\u00f3w center",
    avgTripLengthKm: 14.0,
    idleRiskMinutes: 15,
    rainMultiplier: 1.0,
    eventSensitivity: 0.1,
    airportSensitivity: 0.1,
    notes: "Tourist destination. Long rides back to Krak\u00f3w but dead-end location. No return rides.",
  },
  {
    id: "stare_miasto_north",
    name: "Old Town North (Basztowa)",
    lat: 50.0660,
    lng: 19.9380,
    macroZoneId: "old_town",
    bestPhases: ["morning_rush", "evening_rush", "evening"],
    weekdayDemandByHour: [1, 0, 0, 0, 0, 1, 3, 5, 7, 6, 5, 5, 5, 5, 5, 5, 6, 7, 7, 6, 5, 4, 3, 2],
    weekendDemandByHour: [1, 1, 0, 0, 0, 0, 1, 3, 4, 5, 6, 6, 6, 6, 5, 5, 6, 7, 7, 7, 6, 5, 4, 2],
    oversupplyRisk: "medium",
    likelyDirection: "Station or suburbs",
    avgTripLengthKm: 4.5,
    idleRiskMinutes: 8,
    rainMultiplier: 1.5,
    eventSensitivity: 0.5,
    airportSensitivity: 0.2,
    notes: "Planty gardens edge. Good flow-through zone connecting station to Old Town.",
  },
  {
    id: "kazimierz_south",
    name: "Kazimierz South (Nadwi\u015bla\u0144ska)",
    lat: 50.0480,
    lng: 19.9420,
    macroZoneId: "kazimierz",
    bestPhases: ["evening", "late_night"],
    weekdayDemandByHour: [1, 1, 0, 0, 0, 0, 0, 1, 2, 3, 3, 4, 4, 4, 3, 3, 4, 5, 6, 7, 7, 6, 5, 3],
    weekendDemandByHour: [2, 2, 1, 0, 0, 0, 0, 0, 1, 3, 4, 5, 5, 5, 4, 4, 5, 6, 8, 9, 8, 7, 6, 4],
    oversupplyRisk: "low",
    likelyDirection: "Podg\u00f3rze or suburbs",
    avgTripLengthKm: 4.8,
    idleRiskMinutes: 7,
    rainMultiplier: 1.4,
    eventSensitivity: 0.6,
    airportSensitivity: 0.1,
    notes: "Riverbank nightlife area. Good ride quality, longer trips than central Kazimierz.",
  },
  {
    id: "agh_university",
    name: "AGH University",
    lat: 50.0663,
    lng: 19.9129,
    macroZoneId: "krowodrza",
    bestPhases: ["morning_rush", "afternoon"],
    weekdayDemandByHour: [0, 0, 0, 0, 0, 1, 2, 5, 6, 5, 4, 3, 3, 4, 4, 5, 5, 4, 3, 2, 2, 1, 0, 0],
    weekendDemandByHour: [0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 1, 0, 0],
    oversupplyRisk: "low",
    likelyDirection: "Center or student housing",
    avgTripLengthKm: 3.5,
    idleRiskMinutes: 8,
    rainMultiplier: 1.6,
    eventSensitivity: 0.2,
    airportSensitivity: 0.1,
    notes: "University campus. Student rides are shorter but consistent during term. Rain boosts significantly.",
  },
];

export const LOOP_DEFINITIONS: LoopDefinition[] = [
  {
    id: "central_tourist",
    name: "Central Tourist Loop",
    waypoints: [
      { name: "Old Town North", lat: 50.0660, lng: 19.9380, instruction: "Cruise Basztowa toward station for hotel pickups" },
      { name: "Krak\u00f3w G\u0142\u00f3wny Station", lat: 50.0681, lng: 19.9467, instruction: "Check station exit area for arriving passengers" },
      { name: "Rynek G\u0142\u00f3wny", lat: 50.0614, lng: 19.9372, instruction: "Pass through Rynek, do not wait here" },
      { name: "Wawel Area", lat: 50.0540, lng: 19.9352, instruction: "Cruise Grodzka toward Wawel for tourist pickups" },
      { name: "Kazimierz Center", lat: 50.0512, lng: 19.9448, instruction: "Loop through Szeroka and Miodowa for restaurant rides" },
    ],
    idealPhases: ["midday", "afternoon"],
    description: "Connects the four main tourist hotspots in a natural flow",
    whyItWorks: "Follows tourist movement pattern: station arrival, Old Town sightseeing, Wawel visit, Kazimierz dining",
    riskConditions: "Oversupply at Rynek during peak hours. Skip Rynek waypoint if demand drops below moderate.",
    abandonWhen: "Phase transitions to evening_rush or demand shifts to residential zones",
  },
  {
    id: "nightlife_corridor",
    name: "Nightlife Corridor Loop",
    waypoints: [
      { name: "Kazimierz Center", lat: 50.0512, lng: 19.9448, instruction: "Start at Plac Nowy area for bar exits" },
      { name: "Kazimierz South", lat: 50.0480, lng: 19.9420, instruction: "Sweep Nadwi\u015bla\u0144ska for riverbank bar pickups" },
      { name: "Podg\u00f3rze Center", lat: 50.0440, lng: 19.9500, instruction: "Cross bridge, check Podg\u00f3rze bar strip" },
      { name: "Rynek G\u0142\u00f3wny", lat: 50.0614, lng: 19.9372, instruction: "Cruise through for late restaurant exits" },
      { name: "Old Town North", lat: 50.0660, lng: 19.9380, instruction: "Check hotel returns near Planty" },
    ],
    idealPhases: ["evening", "late_night"],
    description: "Covers the three main nightlife zones with bridge connection",
    whyItWorks: "Nightlife moves from restaurants (Kazimierz) to bars (South) to clubs (Podg\u00f3rze) with Old Town hotel returns",
    riskConditions: "Oversupply in Rynek after midnight. If queued at Rynek, skip to Kazimierz.",
    abandonWhen: "Demand drops below low in all nightlife zones or shift phase moves to overnight",
  },
  {
    id: "commuter_east",
    name: "East Commuter Loop",
    waypoints: [
      { name: "Zab\u0142ocie Hub", lat: 50.0470, lng: 19.9580, instruction: "Pick up office workers heading to center" },
      { name: "Podg\u00f3rze Center", lat: 50.0440, lng: 19.9500, instruction: "Residential pickups heading north" },
      { name: "Krak\u00f3w G\u0142\u00f3wny Station", lat: 50.0681, lng: 19.9467, instruction: "Station drop-offs, pick up arriving commuters" },
      { name: "Old Town North", lat: 50.0660, lng: 19.9380, instruction: "Business district drop-offs" },
      { name: "Galeria Krakowska", lat: 50.0678, lng: 19.9450, instruction: "Shopping mall pickups heading suburban" },
    ],
    idealPhases: ["morning_rush", "evening_rush"],
    description: "Follows the east-to-center commuter flow with station hub",
    whyItWorks: "Natural commuter corridor: Zab\u0142ocie/Podg\u00f3rze offices to center, then station throughput",
    riskConditions: "Station queue can be long during peak. Cruise past rather than waiting if queue > 5 cars.",
    abandonWhen: "Rush hour ends and demand pattern shifts to tourist/leisure",
  },
  {
    id: "airport_premium",
    name: "Airport Premium Loop",
    waypoints: [
      { name: "Airport Feeder", lat: 50.0750, lng: 19.8200, instruction: "Position on Balice road before flight wave" },
      { name: "KRK Airport", lat: 50.0777, lng: 19.7848, instruction: "Queue at arrivals only if wave confirmed" },
      { name: "Bronowice Mall", lat: 50.0830, lng: 19.8900, instruction: "Backup pickups if airport queue too long" },
      { name: "Krowodrza G\u00f3rka", lat: 50.0850, lng: 19.9100, instruction: "Residential pickups heading to center/airport" },
    ],
    idealPhases: ["early_morning", "morning_rush", "evening"],
    description: "Airport-centric loop with western residential backup",
    whyItWorks: "Combines high-value airport rides with western residential demand as backup. Feeder position avoids blind queue.",
    riskConditions: "Blind queue at airport can waste 20+ minutes. Only queue when flight data confirms arrivals.",
    abandonWhen: "No flight arrivals for 45+ minutes or demand shifts to city center",
  },
  {
    id: "event_surge",
    name: "Event Surge Loop",
    waypoints: [
      { name: "Tauron Arena", lat: 50.0692, lng: 20.0108, instruction: "Pre-position 15min before event end at exit roads" },
      { name: "Nowa Huta Centrum", lat: 50.0725, lng: 20.0380, instruction: "Backup if Arena oversupplied" },
      { name: "ICE Krak\u00f3w", lat: 50.0518, lng: 19.9290, instruction: "Congress/conference exits, business travelers" },
      { name: "Krak\u00f3w G\u0142\u00f3wny Station", lat: 50.0681, lng: 19.9467, instruction: "Event-goers heading to trains or hotels" },
    ],
    idealPhases: ["evening", "late_night"],
    description: "Targets the two major event venues with station backup",
    whyItWorks: "Event endings create 15-30min surge windows. Pre-positioning captures first wave before other drivers arrive.",
    riskConditions: "Without active events, these zones are dead. Only use when event data confirms active events.",
    abandonWhen: "Event surge dissipates (15min after event end) or no events scheduled",
  },
];

export const GEOGRAPHIC_TRAPS: TrapDefinition[] = [
  {
    id: "trap_rynek_center_wait",
    name: "Rynek Center Idle Trap",
    category: "geographic",
    lat: 50.0614,
    lng: 19.9372,
    whyAttractive: "Feels like the busiest spot in the city with constant tourist foot traffic",
    whyItHurts: "High oversupply of drivers. Average idle wait 12+ minutes. Short trips dominate. Restricted vehicle access adds friction.",
    whatToDoInstead: "Cruise through Rynek without stopping. Move to Kazimierz or station edge where supply is lower.",
    severity: "high",
    relevantPhases: ["midday", "afternoon", "evening"],
    triggerCondition: "Driver stationary within 200m of Rynek for more than 8 minutes",
  },
  {
    id: "trap_airport_blind_queue",
    name: "Airport Blind Queue",
    category: "geographic",
    lat: 50.0777,
    lng: 19.7848,
    whyAttractive: "Airport rides pay well (14+ km to center). Feels like guaranteed high-value fare.",
    whyItHurts: "Without flight arrival data, queue can be 20-40 minutes. Effective hourly rate drops significantly. No alternative pickups nearby.",
    whatToDoInstead: "Check flight arrival schedule. Position at Airport Feeder zone on Balice road and enter queue only when wave confirmed.",
    severity: "high",
    relevantPhases: ["early_morning", "morning_rush", "evening"],
    triggerCondition: "Driver at airport without confirmed flight arrivals within 20 minutes",
  },
  {
    id: "trap_tauron_parking",
    name: "Tauron Arena Parking Choke",
    category: "geographic",
    lat: 50.0692,
    lng: 20.0108,
    whyAttractive: "Thousands of people leaving at once creates a perception of unlimited demand",
    whyItHurts: "Parking lot gridlock. Access roads jam for 15-20min after event end. Drivers stuck in traffic miss the surge window.",
    whatToDoInstead: "Position on exit roads (al. Pokoju) 15min before event end, not in the parking area. Catch passengers walking out to main roads.",
    severity: "high",
    relevantPhases: ["evening", "late_night"],
    triggerCondition: "Driver in Tauron parking lot within 30 minutes of event end",
  },
  {
    id: "trap_kazimierz_narrow",
    name: "Kazimierz Narrow Streets",
    category: "geographic",
    lat: 50.0520,
    lng: 19.9460,
    whyAttractive: "Heart of nightlife district with bars on every corner",
    whyItHurts: "One-way narrow streets cause pickup friction. Double-parked cars block flow. Passengers struggle to find you.",
    whatToDoInstead: "Wait on Starowi\u015blna or Krakowska (wider streets at Kazimierz edges) and have passengers walk 1-2 minutes to you.",
    severity: "medium",
    relevantPhases: ["evening", "late_night"],
    triggerCondition: "Driver navigating inner Kazimierz streets during peak nightlife hours",
  },
  {
    id: "trap_station_taxi_line",
    name: "Station Official Taxi Line",
    category: "geographic",
    lat: 50.0675,
    lng: 19.9480,
    whyAttractive: "Constant flow of arriving train passengers with luggage",
    whyItHurts: "Official taxi queue moves slowly. App-based pickups compete with licensed taxis. Passengers often pre-book. Average wait 15+ minutes.",
    whatToDoInstead: "Cruise past station exits on Pawia or Basztowa. Pick up passengers who walk out of the station area rather than queuing.",
    severity: "medium",
    relevantPhases: ["morning_rush", "afternoon", "evening_rush"],
    triggerCondition: "Driver stationary near station taxi rank for more than 10 minutes",
  },
  {
    id: "trap_mall_parking_lot",
    name: "Galeria Krakowska Parking",
    category: "geographic",
    lat: 50.0680,
    lng: 19.9440,
    whyAttractive: "Shopping center with high foot traffic feels like guaranteed rides",
    whyItHurts: "Underground parking makes pickup coordination difficult. Passengers request specific levels. Signal drops in parking structure. 8+ min average wait.",
    whatToDoInstead: "Wait at street-level exits on Pawia. Let customers come to you at the surface.",
    severity: "medium",
    relevantPhases: ["midday", "afternoon", "evening_rush"],
    triggerCondition: "Driver entering mall parking structure to wait for rides",
  },
  {
    id: "trap_wieliczka_dead_end",
    name: "Wieliczka Dead End",
    category: "geographic",
    lat: 49.9833,
    lng: 20.0556,
    whyAttractive: "Tourist site with passengers needing 14km rides back to Krak\u00f3w",
    whyItHurts: "No return rides from Wieliczka. After drop-off, 14km dead-head back to Krak\u00f3w with zero earnings. Net effective rate drops sharply.",
    whatToDoInstead: "Accept Wieliczka rides only if already nearby or if the fare compensates for the dead return. Do not drive to Wieliczka hoping for a fare.",
    severity: "high",
    relevantPhases: ["midday", "afternoon"],
    triggerCondition: "Driver heading to Wieliczka without a confirmed ride",
  },
  {
    id: "trap_nowa_huta_deep",
    name: "Deep Nowa Huta Residential",
    category: "geographic",
    lat: 50.0750,
    lng: 20.0500,
    whyAttractive: "Ride drops off here, feels efficient to wait for next local ride",
    whyItHurts: "Sparse demand in deep residential Nowa Huta. Average idle 15+ minutes. Next ride likely another long dead-head to center.",
    whatToDoInstead: "After Nowa Huta drop-off, immediately reposition toward Tauron Arena or Zab\u0142ocie. Do not idle in residential blocks.",
    severity: "medium",
    relevantPhases: ["midday", "afternoon", "evening"],
    triggerCondition: "Driver stationary in deep Nowa Huta for more than 7 minutes",
  },
  {
    id: "trap_planty_ring_circle",
    name: "Planty Ring Circling",
    category: "geographic",
    lat: 50.0630,
    lng: 19.9350,
    whyAttractive: "Circling the Planty ring road feels productive because you pass many locations",
    whyItHurts: "Fuel cost of continuous circling. No stops mean passengers cannot reach you. Other drivers at actual pickup points get rides first.",
    whatToDoInstead: "Pick one strategic position (station edge, Basztowa, or Kazimierz approach) and wait briefly, then reposition if no ride in 5 minutes.",
    severity: "medium",
    relevantPhases: ["midday", "afternoon", "evening"],
    triggerCondition: "Driver completing more than 2 full Planty ring circuits without a ride",
  },
  {
    id: "trap_ice_congress_empty",
    name: "ICE Congress No-Event Wait",
    category: "geographic",
    lat: 50.0518,
    lng: 19.9290,
    whyAttractive: "Large venue area with good road access feels like it should have demand",
    whyItHurts: "Without an active congress or event, the area is dead. D\u0119bniki residential demand is minimal.",
    whatToDoInstead: "Check event calendar. Only position here when events are confirmed. Otherwise, move to Kazimierz or Wawel area.",
    severity: "medium",
    relevantPhases: ["afternoon", "evening"],
    triggerCondition: "Driver waiting near ICE Krak\u00f3w without active event within 2 hours",
  },
];

export const BEHAVIORAL_TRAPS: TrapDefinition[] = [
  {
    id: "trap_idle_oversupply",
    name: "Idle in Oversupplied Zone",
    category: "behavioral",
    whyAttractive: "Staying put feels less risky than repositioning. The zone was busy earlier.",
    whyItHurts: "Every minute idle in an oversupplied zone reduces effective hourly rate. Other drivers are also waiting, creating a race to the bottom.",
    whatToDoInstead: "If idle for more than 8 minutes in a zone marked as high oversupply, reposition to the nearest moderate-demand zone.",
    severity: "high",
    relevantPhases: ["midday", "afternoon", "evening", "late_night"],
    triggerCondition: "Driver idle > 11 minutes in a zone with oversupply risk 'high'",
  },
  {
    id: "trap_weak_outbound_final",
    name: "Weak Outbound Rides Late in Shift",
    category: "behavioral",
    whyAttractive: "Any ride feels better than no ride when shift end approaches",
    whyItHurts: "Accepting a low-rated outbound ride in the final 2 hours means returning to a productive zone takes 20-30 minutes, leaving less time for better rides.",
    whatToDoInstead: "In the final 2 hours, stay within high-demand zones and reject rides that pull you to low-demand suburbs.",
    severity: "high",
    relevantPhases: ["evening", "late_night"],
    triggerCondition: "Accepting outbound rides with reject/weak score in final 2 hours of shift",
  },
  {
    id: "trap_loop_abandonment",
    name: "Premature Loop Abandonment",
    category: "behavioral",
    whyAttractive: "A single quiet waypoint makes the whole loop feel ineffective",
    whyItHurts: "Loops are designed as complete circuits. Abandoning mid-loop means missing the high-demand waypoints that compensate for quiet ones.",
    whatToDoInstead: "Complete at least one full loop circuit before evaluating effectiveness. If two full circuits yield no rides, then switch.",
    severity: "medium",
    relevantPhases: ["morning_rush", "midday", "afternoon", "evening_rush"],
    triggerCondition: "Driver leaving assigned loop during strong corridor phase more than twice per shift",
  },
  {
    id: "trap_consecutive_rejects",
    name: "Accepting Consecutive Weak Rides",
    category: "behavioral",
    whyAttractive: "Fear of missing out. Each individual ride feels like it could be the exception.",
    whyItHurts: "Three consecutive reject-scored rides typically means 30-45 minutes at below-acceptable effective rate with poor zone positioning afterward.",
    whatToDoInstead: "After two consecutive weak/reject-scored rides, pause and reposition to a higher-demand zone before accepting the next ride.",
    severity: "medium",
    relevantPhases: ["midday", "afternoon", "evening"],
    triggerCondition: "Driver accepts 3+ consecutive rides scored as reject or weak",
  },
  {
    id: "trap_ignoring_reposition",
    name: "Ignoring Reposition Guidance",
    category: "behavioral",
    whyAttractive: "Current location feels comfortable. Moving costs fuel and time without a guaranteed ride.",
    whyItHurts: "Reposition recommendations are based on demand data. Ignoring them consistently leads to 15-25% lower effective rates over a shift.",
    whatToDoInstead: "Follow reposition guidance, especially when confidence is above 60%. Track outcomes to build trust in recommendations.",
    severity: "high",
    relevantPhases: ["morning_rush", "midday", "afternoon", "evening_rush", "evening"],
    triggerCondition: "Driver ignores reposition recommendations for more than 20 minutes consecutively",
  },
];

export const TEMPORAL_TRAPS: TrapDefinition[] = [
  {
    id: "trap_early_evening_suburb",
    name: "Early Evening Suburb Trap",
    category: "temporal",
    whyAttractive: "Suburb rides between 17-19h pay well individually due to distance",
    whyItHurts: "Evening rush (17-19h) is the transition to high-earning evening phase. Getting pulled to a suburb means missing the demand wave in nightlife zones. Return trip wastes 20+ minutes.",
    whatToDoInstead: "Between 17-19h, stay within core zones (Old Town, Kazimierz, station corridor). Let the evening demand come to you.",
    severity: "high",
    relevantPhases: ["evening_rush"],
    triggerCondition: "Driver accepting suburban rides between 17:00-19:00",
  },
  {
    id: "trap_surge_no_traffic_check",
    name: "Chasing Surge Without Traffic Check",
    category: "temporal",
    whyAttractive: "Surge indicator in a zone 3km away looks like easy higher earnings",
    whyItHurts: "During rush hours (7-9h, 16-19h), a 3km drive can take 15-25 minutes in traffic. By the time you arrive, the surge has dissipated or other drivers have filled it.",
    whatToDoInstead: "Only reposition toward surge zones that are less than 5 minutes drive in current traffic. Trust your current zone if demand is moderate or better.",
    severity: "medium",
    relevantPhases: ["morning_rush", "evening_rush"],
    triggerCondition: "Driver repositioning toward surge zone more than 10 minutes drive away during rush hour",
  },
  {
    id: "trap_unprotected_final_hours",
    name: "Unprotected Final Shift Hours",
    category: "temporal",
    whyAttractive: "Continuing normal ride acceptance pattern feels consistent",
    whyItHurts: "The last 2 hours of a shift have outsized impact on overall effective rate. Poor zone positioning or long suburban rides in this window cannot be recovered.",
    whatToDoInstead: "In the final 2 hours, tighten ride acceptance criteria. Stay in high-demand zones. Reject rides that would pull you more than 5km from core areas.",
    severity: "high",
    relevantPhases: ["evening", "late_night"],
    triggerCondition: "Driver in final 2 hours of shift accepting rides that move them outside core zone radius",
  },
];

export const ALL_TRAPS: TrapDefinition[] = [
  ...GEOGRAPHIC_TRAPS,
  ...BEHAVIORAL_TRAPS,
  ...TEMPORAL_TRAPS,
];

export interface CalibrationTestCase {
  id: string;
  description: string;
  rideOffer: RideOffer;
  context: {
    hour: number;
    isWeekend: boolean;
    driverLat: number;
    driverLng: number;
    currentPhase: string;
    eventNearby: boolean;
  };
  expectedScoreRange: [number, number];
  expectedLabel: RideScoreLabel;
  reasoning: string;
}

export const CALIBRATION_TEST_CASES: CalibrationTestCase[] = [
  {
    id: "cal_01_airport_morning",
    description: "Airport ride from station during morning rush",
    rideOffer: {
      pickupLat: 50.0681,
      pickupLng: 19.9467,
      pickupName: "Krak\u00f3w G\u0142\u00f3wny Station",
      dropoffLat: 50.0777,
      dropoffLng: 19.7848,
      dropoffName: "KRK Airport",
      estimatedFarePLN: 65,
      estimatedDurationMin: 25,
      estimatedDistanceKm: 14.5,
    },
    context: {
      hour: 8,
      isWeekend: false,
      driverLat: 50.0670,
      driverLng: 19.9460,
      currentPhase: "morning_rush",
      eventNearby: false,
    },
    expectedScoreRange: [4, 8],
    expectedLabel: "accept",
    reasoning: "Good fare but leaves driver at airport with uncertain return. Morning rush means missing commuter demand in center.",
  },
  {
    id: "cal_02_kazimierz_short_evening",
    description: "Short Kazimierz ride during evening peak",
    rideOffer: {
      pickupLat: 50.0512,
      pickupLng: 19.9448,
      pickupName: "Kazimierz Center",
      dropoffLat: 50.0540,
      dropoffLng: 19.9352,
      dropoffName: "Wawel Area",
      estimatedFarePLN: 12,
      estimatedDurationMin: 6,
      estimatedDistanceKm: 1.5,
    },
    context: {
      hour: 20,
      isWeekend: true,
      driverLat: 50.0510,
      driverLng: 19.9440,
      currentPhase: "evening",
      eventNearby: false,
    },
    expectedScoreRange: [2, 6],
    expectedLabel: "accept",
    reasoning: "Short trip but keeps driver in high-demand tourist corridor. Good chaining potential. Weekend evening is prime time.",
  },
  {
    id: "cal_03_nowa_huta_outbound_night",
    description: "Long outbound ride to deep Nowa Huta at night",
    rideOffer: {
      pickupLat: 50.0614,
      pickupLng: 19.9372,
      pickupName: "Rynek G\u0142\u00f3wny",
      dropoffLat: 50.0750,
      dropoffLng: 20.0500,
      dropoffName: "Nowa Huta Residential",
      estimatedFarePLN: 32,
      estimatedDurationMin: 20,
      estimatedDistanceKm: 9.0,
    },
    context: {
      hour: 23,
      isWeekend: true,
      driverLat: 50.0610,
      driverLng: 19.9370,
      currentPhase: "late_night",
      eventNearby: false,
    },
    expectedScoreRange: [-3, 0],
    expectedLabel: "weak",
    reasoning: "Drops driver in dead zone at night. No return rides. Long dead-head back. Misses nightlife surge window.",
  },
  {
    id: "cal_04_wieliczka_tourist_midday",
    description: "Wieliczka Salt Mine ride during midday",
    rideOffer: {
      pickupLat: 50.0614,
      pickupLng: 19.9372,
      pickupName: "Rynek G\u0142\u00f3wny",
      dropoffLat: 49.9833,
      dropoffLng: 20.0556,
      dropoffName: "Wieliczka Salt Mine",
      estimatedFarePLN: 55,
      estimatedDurationMin: 30,
      estimatedDistanceKm: 14.0,
    },
    context: {
      hour: 11,
      isWeekend: false,
      driverLat: 50.0612,
      driverLng: 19.9370,
      currentPhase: "midday",
      eventNearby: false,
    },
    expectedScoreRange: [-1, 3],
    expectedLabel: "neutral",
    reasoning: "Decent fare but dead-end destination. No return rides from Wieliczka. 14km dead-head back to productive zones.",
  },
  {
    id: "cal_05_zablocie_to_station_rush",
    description: "Zab\u0142ocie to station during morning rush",
    rideOffer: {
      pickupLat: 50.0470,
      pickupLng: 19.9580,
      pickupName: "Zab\u0142ocie Hub",
      dropoffLat: 50.0681,
      dropoffLng: 19.9467,
      dropoffName: "Krak\u00f3w G\u0142\u00f3wny Station",
      estimatedFarePLN: 18,
      estimatedDurationMin: 12,
      estimatedDistanceKm: 3.5,
    },
    context: {
      hour: 8,
      isWeekend: false,
      driverLat: 50.0465,
      driverLng: 19.9575,
      currentPhase: "morning_rush",
      eventNearby: false,
    },
    expectedScoreRange: [5, 9],
    expectedLabel: "strong_accept",
    reasoning: "Strong commuter ride. Repositions driver to station hub where next ride is almost immediate. Peak demand phase.",
  },
  {
    id: "cal_06_event_exit_tauron",
    description: "Ride from Tauron Arena during event exit",
    rideOffer: {
      pickupLat: 50.0692,
      pickupLng: 20.0108,
      pickupName: "Tauron Arena",
      dropoffLat: 50.0614,
      dropoffLng: 19.9372,
      dropoffName: "Rynek G\u0142\u00f3wny",
      estimatedFarePLN: 28,
      estimatedDurationMin: 15,
      estimatedDistanceKm: 5.5,
    },
    context: {
      hour: 21,
      isWeekend: false,
      driverLat: 50.0690,
      driverLng: 20.0100,
      currentPhase: "evening",
      eventNearby: true,
    },
    expectedScoreRange: [5, 9],
    expectedLabel: "strong_accept",
    reasoning: "Event exit ride repositions to Old Town. High demand continuation. Good fare for distance. Event surge pricing likely.",
  },
  {
    id: "cal_07_suburb_to_suburb",
    description: "Suburban cross-ride during afternoon lull",
    rideOffer: {
      pickupLat: 50.0960,
      pickupLng: 19.9280,
      pickupName: "Pr\u0105dnik Bia\u0142y",
      dropoffLat: 50.0370,
      dropoffLng: 19.9650,
      dropoffName: "P\u0142asz\u00f3w",
      estimatedFarePLN: 25,
      estimatedDurationMin: 22,
      estimatedDistanceKm: 8.0,
    },
    context: {
      hour: 14,
      isWeekend: false,
      driverLat: 50.0955,
      driverLng: 19.9275,
      currentPhase: "afternoon",
      eventNearby: false,
    },
    expectedScoreRange: [-4, -1],
    expectedLabel: "reject",
    reasoning: "Suburb-to-suburb ride. Both zones have low afternoon demand. Leaves driver stranded in P\u0142asz\u00f3w with no nearby demand.",
  },
  {
    id: "cal_08_rain_kazimierz_pickup",
    description: "Short Kazimierz ride during rain",
    rideOffer: {
      pickupLat: 50.0512,
      pickupLng: 19.9448,
      pickupName: "Kazimierz Center",
      dropoffLat: 50.0614,
      dropoffLng: 19.9372,
      dropoffName: "Rynek G\u0142\u00f3wny",
      estimatedFarePLN: 15,
      estimatedDurationMin: 8,
      estimatedDistanceKm: 2.0,
    },
    context: {
      hour: 19,
      isWeekend: true,
      driverLat: 50.0515,
      driverLng: 19.9450,
      currentPhase: "evening",
      eventNearby: false,
    },
    expectedScoreRange: [3, 7],
    expectedLabel: "accept",
    reasoning: "Short ride but keeps driver in premium zone. Rain boosts demand. Weekend evening is high-demand. Quick turnaround.",
  },
  {
    id: "cal_09_ice_conference_hotel",
    description: "ICE Congress to hotel ride, business traveler",
    rideOffer: {
      pickupLat: 50.0518,
      pickupLng: 19.9290,
      pickupName: "ICE Krak\u00f3w",
      dropoffLat: 50.0650,
      dropoffLng: 19.9400,
      dropoffName: "Hotel Stary (Old Town)",
      estimatedFarePLN: 20,
      estimatedDurationMin: 10,
      estimatedDistanceKm: 2.5,
    },
    context: {
      hour: 17,
      isWeekend: false,
      driverLat: 50.0520,
      driverLng: 19.9295,
      currentPhase: "evening_rush",
      eventNearby: true,
    },
    expectedScoreRange: [4, 8],
    expectedLabel: "accept",
    reasoning: "Business traveler, good tip probability. Repositions to Old Town for evening rush. Conference exit provides chaining.",
  },
  {
    id: "cal_10_overnight_airport_early",
    description: "Early morning airport ride from hotel district",
    rideOffer: {
      pickupLat: 50.0650,
      pickupLng: 19.9400,
      pickupName: "Old Town Hotel District",
      dropoffLat: 50.0777,
      dropoffLng: 19.7848,
      dropoffName: "KRK Airport",
      estimatedFarePLN: 70,
      estimatedDurationMin: 22,
      estimatedDistanceKm: 14.0,
    },
    context: {
      hour: 5,
      isWeekend: false,
      driverLat: 50.0648,
      driverLng: 19.9398,
      currentPhase: "early_morning",
      eventNearby: false,
    },
    expectedScoreRange: [5, 10],
    expectedLabel: "strong_accept",
    reasoning: "Premium early morning airport ride. High fare. Low competition at 5am. Can queue at airport for return ride from first arrivals.",
  },
];

export const ACTION_COOLDOWN_MAP: Record<CopilotAction, number> = { ...ACTION_COOLDOWNS };
