import { Ionicons } from "@expo/vector-icons";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { FeatureGate } from "@/components/FeatureGate";
import { fetchEarningsStats, type EarningsStats } from "@/lib/api";
import { theme } from "@/lib/theme";

export default function EarningsScreen(){return <FeatureGate premium><EarningsContent/></FeatureGate>}
function EarningsContent(){const[stats,setStats]=useState<EarningsStats|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const load=async()=>{setLoading(true);try{setStats(await fetchEarningsStats());setError(null)}catch(e){setError(e instanceof Error?e.message:"Dane niedostępne")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);const max=Math.max(1,...(stats?.topZones.map(z=>z.amount)??[1]));return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><View style={s.header}><View><Text style={s.eyebrow}>PERFORMANCE</Text><Text style={s.title}>Zarobki</Text></View><Pressable onPress={()=>void load()} style={s.refresh}><Ionicons name="refresh" size={18} color={theme.primary}/></Pressable></View>{loading&&!stats?<ActivityIndicator color={theme.primary} style={{margin:32}}/>:null}{error&&!stats?<Text style={s.error}>{error} Statystyki konta mogą wymagać zalogowanej sesji.</Text>:null}<View style={s.metrics}><Metric label="Łącznie" value={stats?`${stats.totalEarnings.toFixed(0)} PLN`:"—"}/><Metric label="Przejazdy" value={stats?String(stats.totalTrips):"—"}/><Metric label="Śr./kurs" value={stats?`${stats.averagePerTrip.toFixed(1)} PLN`:"—"}/></View><Text style={s.section}>Najlepsze strefy</Text><View style={s.card}>{stats?.topZones.length?stats.topZones.map((z,i)=><View key={`${z.name}-${i}`} style={s.row}><Text style={s.rank}>{i+1}</Text><View style={{flex:1}}><View style={s.line}><Text style={s.name}>{z.name}</Text><Text style={s.amount}>{z.amount.toFixed(0)} PLN</Text></View><View style={s.bar}><View style={[s.fill,{width:`${Math.max(5,z.amount/max*100)}%`}]}/></View></View></View>):<Text style={s.empty}>Po synchronizacji konta pojawią się tutaj statystyki.</Text>}</View><Text style={s.note}>Import CSV pozostaje w wersji webowej; Android korzysta z tego samego API.</Text></ScrollView></SafeAreaView>}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:theme.background},content:{padding:18,paddingBottom:34},header:{flexDirection:"row",justifyContent:"space-between"},eyebrow:{color:theme.primary,fontSize:10,fontWeight:"900",letterSpacing:1.2},title:{color:theme.text,fontSize:30,fontWeight:"900",marginTop:4},refresh:{width:40,height:40,borderRadius:13,alignItems:"center",justifyContent:"center",backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border},error:{color:theme.warning,fontSize:10,lineHeight:15,marginTop:14},metrics:{flexDirection:"row",gap:8,marginTop:16},metric:{flex:1,minHeight:82,padding:11,borderRadius:15,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,justifyContent:"space-between"},metricValue:{color:theme.text,fontSize:15,fontWeight:"900"},metricLabel:{color:theme.muted,fontSize:9},section:{color:theme.text,fontSize:17,fontWeight:"900",marginTop:22,marginBottom:8},card:{backgroundColor:theme.surface,borderRadius:17,borderWidth:1,borderColor:theme.border,overflow:"hidden"},row:{flexDirection:"row",alignItems:"center",gap:9,padding:12,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:theme.border},rank:{width:20,color:theme.primary,fontWeight:"900"},line:{flexDirection:"row",justifyContent:"space-between"},name:{color:theme.text,fontSize:11,fontWeight:"800"},amount:{color:theme.primary,fontSize:10,fontWeight:"900"},bar:{height:4,backgroundColor:theme.surfaceRaised,borderRadius:4,marginTop:6,overflow:"hidden"},fill:{height:4,backgroundColor:theme.primary},empty:{color:theme.muted,fontSize:10,padding:18,textAlign:"center"},note:{color:theme.muted,fontSize:9.5,lineHeight:14,marginTop:14}});
