import { Ionicons } from "@expo/vector-icons";
import { useMemo, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { MapExperience } from "@/components/MapExperience";
import { NextMoveCard } from "@/components/NextMoveCard";
import { TrafficPulseField } from "@/components/TrafficPulseField";
import { useDeviceLocation } from "@/hooks/use-device-location";
import { useLiveHeat } from "@/hooks/use-live-heat";
import { theme } from "@/lib/theme";

const OFFSETS=[0,3,6,12] as const;
export default function MapScreen(){
 const[hoursAhead,setHoursAhead]=useState<(typeof OFFSETS)[number]>(0);const[showTraffic,setShowTraffic]=useState(true);const{data,error,loading,refresh}=useLiveHeat(hoursAhead);const{position,status}=useDeviceLocation();const cells=data?.cells??[];const score=useMemo(()=>Math.round(cells.slice(0,40).reduce((sum,c)=>sum+c.score,0)/Math.max(1,Math.min(cells.length,40))),[cells]);
 return <SafeAreaView edges={["top"]} style={s.screen}><View style={s.header}><View style={s.liveDot}/><View style={{flex:1}}><Text style={s.headerTitle}>{status==="active"?"GPS Active":status==="requesting"?"GPS Locking":"Kraków Grid"}</Text><Text style={s.headerMeta}>Live demand · Kraków</Text></View><Pressable onPress={refresh} style={s.refresh}><Ionicons name="refresh" size={18} color={theme.primary}/></Pressable></View><View style={s.map}><MapExperience cells={cells} position={position}/>{showTraffic?<TrafficPulseField/>:null}<Pressable onPress={()=>setShowTraffic(v=>!v)} style={[s.layer,showTraffic&&s.layerActive]}><Ionicons name="pulse-outline" size={14} color={showTraffic?theme.background:theme.muted}/><Text style={[s.layerText,showTraffic&&s.layerTextActive]}>Ruch</Text></Pressable><View style={s.offsets}>{OFFSETS.map(offset=><Pressable key={offset} onPress={()=>setHoursAhead(offset)} style={[s.offset,hoursAhead===offset&&s.offsetActive]}><Text style={[s.offsetText,hoursAhead===offset&&s.offsetTextActive]}>{offset===0?"LIVE":`+${offset}h`}</Text></Pressable>)}</View>{loading&&!data?<View style={s.state}><ActivityIndicator color={theme.primary}/></View>:null}{error&&!data?<View style={s.state}><Text style={s.error}>{error}</Text></View>:null}<View style={s.card}><NextMoveCard score={score||72} onRefresh={refresh}/></View></View></SafeAreaView>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:theme.background},header:{minHeight:68,paddingHorizontal:16,flexDirection:"row",alignItems:"center",gap:11},liveDot:{width:10,height:10,borderRadius:5,backgroundColor:theme.primary},headerTitle:{color:theme.text,fontSize:18,fontWeight:"900"},headerMeta:{color:theme.muted,fontSize:10,marginTop:2},refresh:{width:38,height:38,borderRadius:12,alignItems:"center",justifyContent:"center",backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border},map:{flex:1,position:"relative"},offsets:{position:"absolute",top:12,alignSelf:"center",flexDirection:"row",gap:4,padding:4,borderRadius:99,backgroundColor:"rgba(10,13,20,0.88)"},offset:{borderRadius:99,paddingHorizontal:9,paddingVertical:6},offsetActive:{backgroundColor:theme.primary},offsetText:{color:theme.muted,fontSize:10,fontWeight:"900"},offsetTextActive:{color:theme.background},layer:{position:"absolute",right:10,top:54,minWidth:72,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:5,padding:8,borderRadius:12,backgroundColor:"rgba(10,13,20,0.84)",borderWidth:1,borderColor:theme.border},layerActive:{backgroundColor:theme.primary,borderColor:theme.primary},layerText:{color:theme.muted,fontSize:10,fontWeight:"900"},layerTextActive:{color:theme.background},state:{position:"absolute",top:"35%",alignSelf:"center",padding:16,borderRadius:16,backgroundColor:"rgba(10,13,20,0.94)"},error:{color:theme.danger,fontSize:11},card:{position:"absolute",left:12,right:12,bottom:12}});
