import { Ionicons } from "@expo/vector-icons";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { FeatureGate } from "@/components/FeatureGate";
import { fetchDayPlan, type DayPlanResponse, type HourBlock } from "@/lib/api";
import { theme } from "@/lib/theme";

const demandColor=(level:HourBlock["demandLevel"])=>level==="surge"||level==="high"?theme.danger:level==="medium"?theme.warning:theme.muted;

export default function PlannerScreen(){
 return <FeatureGate premium><PlannerContent/></FeatureGate>;
}

function PlannerContent(){
 const [tomorrow,setTomorrow]=useState(false),[plan,setPlan]=useState<DayPlanResponse|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[expanded,setExpanded]=useState<number|null>(null);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError(null);fetchDayPlan(tomorrow,controller.signal).then(setPlan).catch((reason:unknown)=>{if(reason instanceof Error&&reason.name==="AbortError")return;setError(reason instanceof Error?reason.message:"Plan dnia jest niedostępny");}).finally(()=>setLoading(false));return()=>controller.abort();},[tomorrow]);
 return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
  <Text style={styles.eyebrow}>DRIVER COPILOT</Text><Text style={styles.title}>Plan dnia</Text><Text style={styles.subtitle}>{plan?`${plan.dayName}, ${plan.date}`:"Optymalny rytm jazdy dla Krakowa"}</Text>
  <View style={styles.segmented}><Pressable onPress={()=>setTomorrow(false)} style={[styles.segment,!tomorrow&&styles.segmentActive]}><Text style={[styles.segmentText,!tomorrow&&styles.segmentTextActive]}>Dzisiaj</Text></Pressable><Pressable onPress={()=>setTomorrow(true)} style={[styles.segment,tomorrow&&styles.segmentActive]}><Text style={[styles.segmentText,tomorrow&&styles.segmentTextActive]}>Jutro</Text></Pressable></View>
  {plan?<View style={styles.tip}><Ionicons name="bulb-outline" size={20} color={theme.primary}/><View style={{flex:1}}><Text style={styles.tipTitle}>Planowanie zmiany</Text><Text style={styles.tipText}>{plan.uberTip}</Text></View></View>:null}
  {plan?.summary?<Text style={styles.summary}>{plan.summary}</Text>:null}
  {loading?<View style={styles.state}><ActivityIndicator size="large" color={theme.primary}/><Text style={styles.stateText}>Budowanie planu…</Text></View>:error?<View style={styles.state}><Text style={styles.stateText}>{error}</Text></View>:<View style={styles.timeline}>{plan?.blocks.map(block=>{const open=expanded===block.hour,color=demandColor(block.demandLevel);return <View key={block.hour}><Pressable onPress={()=>setExpanded(open?null:block.hour)} style={styles.block}><Text style={styles.hour}>{String(block.hour).padStart(2,"0")}:00</Text><View style={[styles.dot,{backgroundColor:color}]}/><View style={{flex:1}}><Text style={styles.zone} numberOfLines={1}>{block.bestZone}</Text><Text style={styles.potential}>{block.earningsPotential}</Text></View><Text style={[styles.level,{color}]}>{block.demandLevel}</Text><Ionicons name={open?"chevron-down":"chevron-forward"} size={15} color={theme.muted}/></Pressable>{open?<View style={styles.details}><Text style={styles.detailTitle}>Platform recommendation</Text><Text style={styles.detail}>{block.platformTip}</Text>{block.events.map((e,i)=><Text key={i} style={styles.detail}>• {e.title} · {e.venue}</Text>)}{block.flights.map((f,i)=><Text key={i} style={styles.detail}>• {f.label} ({f.count})</Text>)}<Text style={[styles.detailTitle,{color:theme.warning}]}>Pro tip</Text><Text style={styles.detail}>{block.proTip}</Text></View>:null}</View>;})}</View>}
 </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:theme.background},content:{padding:18,paddingBottom:34},eyebrow:{color:theme.primary,fontSize:10,fontWeight:"900",letterSpacing:1.3},title:{color:theme.text,fontSize:30,fontWeight:"900",marginTop:5},subtitle:{color:theme.muted,fontSize:12,marginTop:5},segmented:{flexDirection:"row",padding:4,backgroundColor:theme.surface,borderRadius:14,marginTop:16,borderWidth:1,borderColor:theme.border},segment:{flex:1,alignItems:"center",paddingVertical:9,borderRadius:10},segmentActive:{backgroundColor:theme.primary},segmentText:{color:theme.muted,fontSize:11,fontWeight:"900"},segmentTextActive:{color:theme.background},tip:{flexDirection:"row",gap:10,marginTop:13,backgroundColor:"rgba(46,230,166,0.07)",borderRadius:16,padding:13,borderWidth:1,borderColor:"rgba(46,230,166,0.18)"},tipTitle:{color:theme.text,fontSize:12,fontWeight:"900"},tipText:{color:theme.muted,fontSize:10.5,lineHeight:15,marginTop:3},summary:{color:theme.muted,fontSize:11,lineHeight:16,marginVertical:14},state:{alignItems:"center",paddingVertical:48,gap:10},stateText:{color:theme.muted,fontSize:11,textAlign:"center"},timeline:{gap:7,marginTop:14},block:{minHeight:64,flexDirection:"row",alignItems:"center",gap:9,paddingHorizontal:11,borderRadius:15,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border},hour:{width:45,color:theme.text,fontSize:11,fontWeight:"900"},dot:{width:8,height:8,borderRadius:4},zone:{color:theme.text,fontSize:12,fontWeight:"800"},potential:{color:theme.muted,fontSize:9.5,marginTop:3},level:{fontSize:8,fontWeight:"900",textTransform:"uppercase"},details:{marginTop:4,marginLeft:55,padding:12,borderRadius:14,backgroundColor:theme.surfaceRaised,gap:5},detailTitle:{color:theme.primary,fontSize:9.5,fontWeight:"900",marginTop:2},detail:{color:theme.muted,fontSize:9.5,lineHeight:14}});
