import { FormEvent, useEffect, useState } from "react";
import { Link } from "wouter";
import { Cookie, Flag, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";

const KEY="pluspuls_cookie_preferences_v1";
type Prefs={essential:true;functional:boolean;analytics:boolean};

function load():Prefs{try{const p=JSON.parse(localStorage.getItem(KEY)||"null");return{essential:true,functional:p?.functional===true,analytics:p?.analytics===true}}catch{return{essential:true,functional:false,analytics:false}}}

export function TrustDock(){
const [cookieOpen,setCookieOpen]=useState(false),[feedbackOpen,setFeedbackOpen]=useState(false);
const [prefs,setPrefs]=useState<Prefs>({essential:true,functional:false,analytics:false});
const [error,setError]=useState(""),[status,setStatus]=useState(""),[sending,setSending]=useState(false);
useEffect(()=>setPrefs(load()),[]);
function save(next:Prefs){localStorage.setItem(KEY,JSON.stringify({functional:next.functional,analytics:next.analytics,updatedAt:new Date().toISOString()}));setPrefs(next);setCookieOpen(false);window.dispatchEvent(new CustomEvent("pluspuls:cookie-preferences",{detail:next}))}
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");setStatus("");setSending(true);const f=new FormData(e.currentTarget);try{const r=await fetch("/api/trust/report",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:f.get("kind"),message:f.get("message"),contactEmail:f.get("contactEmail")})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||"Reporting channel is not available yet.");setStatus(`Received. Reference: ${b.reference||"accepted"}`);e.currentTarget.reset()}catch(x){setError(x instanceof Error?x.message:"Reporting channel is not available yet.")}finally{setSending(false)}}
return <><div className="fixed bottom-20 right-3 z-50 flex flex-col items-end gap-2 md:bottom-5 md:right-5" aria-label="Trust controls"><button onClick={()=>setFeedbackOpen(true)} className="inline-flex min-h-11 items-center gap-2 rounded-full border border-primary/30 bg-card/95 px-4 text-sm font-semibold shadow-xl backdrop-blur-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><Flag className="h-4 w-4 text-primary"/>Feedback</button><button onClick={()=>setCookieOpen(true)} className="inline-flex min-h-10 items-center gap-2 rounded-full border border-border bg-card/95 px-3 text-xs font-medium text-muted-foreground shadow-lg backdrop-blur-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><Cookie className="h-3.5 w-3.5"/>Cookie settings</button></div>
<Dialog open={cookieOpen} onOpenChange={setCookieOpen}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary"/>Cookie settings</DialogTitle></DialogHeader><p className="text-sm leading-6 text-muted-foreground">Choose optional browser-storage categories. Essential storage remains enabled for secure operation.</p><Pref label="Essential" description="Sign-in, security, session continuity and saved consent choice." checked disabled onChange={()=>{}}/><Pref label="Functional" description="Optional convenience preferences." checked={prefs.functional} onChange={v=>setPrefs({...prefs,functional:v})}/><Pref label="Analytics" description="Optional measurement. Off unless you choose it." checked={prefs.analytics} onChange={v=>setPrefs({...prefs,analytics:v})}/><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>save({essential:true,functional:false,analytics:false})}>Reject optional</Button><Button onClick={()=>save(prefs)}>Save choices</Button><Link href="/trust/cookies" className="inline-flex min-h-10 items-center px-2 text-sm text-primary hover:underline">Cookie policy</Link></div></DialogContent></Dialog>
<Dialog open={feedbackOpen} onOpenChange={setFeedbackOpen}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Feedback & speak up</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={submit}><label className="block text-sm font-medium">Category<select name="kind" className="mt-1.5 min-h-11 w-full rounded-md border border-input bg-background px-3" defaultValue="feedback"><option value="feedback">Product feedback</option><option value="accessibility">Accessibility</option><option value="privacy">Privacy</option><option value="speak-up">Speak up / conduct concern</option></select></label><label className="block text-sm font-medium">Message<textarea name="message" required minLength={10} maxLength={4000} rows={6} className="mt-1.5 w-full rounded-md border border-input bg-background px-3 py-2 leading-6" placeholder="Describe the issue. Do not include passwords, payment credentials or authentication codes."/></label><label className="block text-sm font-medium">Contact email <span className="font-normal text-muted-foreground">(optional)</span><input name="contactEmail" type="email" maxLength={254} className="mt-1.5 min-h-11 w-full rounded-md border border-input bg-background px-3"/></label>{error&&<p role="alert" className="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{status&&<p role="status" className="rounded-md border border-primary/30 bg-primary/10 p-3 text-sm text-primary">{status}</p>}<div className="flex items-center gap-2"><Button type="submit" disabled={sending}>{sending?"Sending…":"Submit"}</Button><Link href="/trust/speak-up" className="text-sm text-primary hover:underline">Reporting guidance</Link></div></form></DialogContent></Dialog></>
}
function Pref({label,description,checked,disabled,onChange}:{label:string;description:string;checked:boolean;disabled?:boolean;onChange:(v:boolean)=>void}){return <label className={`flex items-start justify-between gap-4 rounded-xl border border-border/70 p-4 ${disabled?"opacity-70":"cursor-pointer"}`}><span><span className="block text-sm font-semibold">{label}</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{description}</span></span><input type="checkbox" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)} className="mt-1 h-5 w-5 accent-[hsl(var(--primary))]"/></label>}
